-- =============================================================================
-- Object Name  : AEROSPACE_PARTS_SOURCE
-- Purpose      : DDL for the AEROSPACE_PARTS_SOURCE staging table used as the
--                landing zone for raw aerospace parts inventory data ingested
--                from the source system. This table feeds the
--                SP_LOAD_AEROSPACE_PARTS_SCD1 stored procedure for incremental
--                SCD Type 1 processing into AEROSPACE_PARTS_TARGET.
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-31
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- =============================================================================

-- =============================================================================
-- SECTION 1: DATABASE AND SCHEMA CONTEXT
-- Set the active database and schema for all subsequent DDL statements.
-- =============================================================================

-- Set active database context
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set active schema context
USE SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD;

-- =============================================================================
-- SECTION 2: SOURCE STAGING TABLE DDL
-- Create the AEROSPACE_PARTS_SOURCE staging table if it does not already exist.
-- This table holds raw, unprocessed records loaded from the upstream source
-- system. No transformations are applied at this layer. All columns are
-- nullable to accommodate varying source data quality and allow the stored
-- procedure to apply validation and transformation logic downstream.
-- =============================================================================

-- Create the AEROSPACE_PARTS_SOURCE staging table (idempotent)
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (

    -- -------------------------------------------------------------------------
    -- Primary Business Key
    -- Unique identifier for each aerospace part in the source system.
    -- Used as the merge key in SCD Type 1 processing and deduplication.
    -- -------------------------------------------------------------------------
    PART_NUMBER                 VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Part Descriptive Attributes
    -- Core descriptive fields describing the aerospace part.
    -- -------------------------------------------------------------------------
    PART_NAME                   VARCHAR(255),
    PART_DESCRIPTION            VARCHAR(1000),
    PART_CATEGORY               VARCHAR(100),
    PART_TYPE                   VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Manufacturer Information
    -- Raw manufacturer name as received from the source system.
    -- Will be transformed to CamelCase format in AEROSPACE_PARTS_TARGET
    -- per RULE-006 (CamelCase transformation).
    -- -------------------------------------------------------------------------
    MANUFACTURER                VARCHAR(255),
    MANUFACTURER_CODE           VARCHAR(50),
    MANUFACTURER_COUNTRY        VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Certification and Compliance Attributes
    -- Certification status drives RISK_SCORE derivation (RULE-009).
    -- Expected values: Pending, FAA, EASA, Dual (and potentially others).
    -- -------------------------------------------------------------------------
    CERTIFICATION_STATUS        VARCHAR(100),
    COMPLIANCE_STANDARD         VARCHAR(100),
    REGULATORY_BODY             VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Lifecycle and Installation Attributes
    -- LIFECYCLE_STATUS and INSTALLATION_DATE are used in the exclusion rule
    -- (RULE-005): records where LIFECYCLE_STATUS = 'End of Life' AND
    -- INSTALLATION_DATE < DATEADD(year, -3, CURRENT_DATE) are excluded.
    -- -------------------------------------------------------------------------
    LIFECYCLE_STATUS            VARCHAR(100),
    INSTALLATION_DATE           DATE,
    DECOMMISSION_DATE           DATE,
    END_OF_LIFE_DATE            DATE,

    -- -------------------------------------------------------------------------
    -- Physical Attributes
    -- WEIGHT_KG is subject to null replacement per RULE-007:
    -- NULL or zero values are replaced with 0.01 in AEROSPACE_PARTS_TARGET.
    -- -------------------------------------------------------------------------
    WEIGHT_KG                   NUMBER(18, 4),
    DIMENSIONS_CM               VARCHAR(100),
    MATERIAL_TYPE               VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Pricing and Procurement Attributes
    -- UNIT_PRICE_USD is rounded to 2 decimal places per RULE-008.
    -- LEAD_TIME_DAYS drives RISK_SCORE derivation per RULE-009.
    -- -------------------------------------------------------------------------
    UNIT_PRICE_USD              NUMBER(18, 6),
    CURRENCY_CODE               VARCHAR(10),
    LEAD_TIME_DAYS              NUMBER(10, 0),
    MINIMUM_ORDER_QUANTITY      NUMBER(10, 0),
    REORDER_POINT               NUMBER(10, 0),

    -- -------------------------------------------------------------------------
    -- Inventory and Stock Attributes
    -- Current inventory levels and warehouse location data.
    -- -------------------------------------------------------------------------
    QUANTITY_ON_HAND            NUMBER(18, 0),
    QUANTITY_ON_ORDER           NUMBER(18, 0),
    WAREHOUSE_LOCATION          VARCHAR(100),
    BIN_LOCATION                VARCHAR(50),
    STOCK_STATUS                VARCHAR(50),

    -- -------------------------------------------------------------------------
    -- Supplier Information
    -- Supplier details associated with the aerospace part.
    -- -------------------------------------------------------------------------
    SUPPLIER_NAME               VARCHAR(255),
    SUPPLIER_CODE               VARCHAR(50),
    SUPPLIER_COUNTRY            VARCHAR(100),
    SUPPLIER_CONTRACT_NUMBER    VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Aircraft and Application Compatibility
    -- Defines which aircraft models and systems the part is compatible with.
    -- -------------------------------------------------------------------------
    AIRCRAFT_MODEL_COMPATIBILITY VARCHAR(500),
    SYSTEM_COMPATIBILITY        VARCHAR(500),
    SUBSYSTEM_COMPATIBILITY     VARCHAR(500),
    APPLICATION_TYPE            VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Quality and Inspection Attributes
    -- Quality control and inspection tracking fields.
    -- -------------------------------------------------------------------------
    QUALITY_GRADE               VARCHAR(50),
    INSPECTION_INTERVAL_DAYS    NUMBER(10, 0),
    LAST_INSPECTION_DATE        DATE,
    NEXT_INSPECTION_DATE        DATE,
    INSPECTION_STATUS           VARCHAR(50),

    -- -------------------------------------------------------------------------
    -- Maintenance and Overhaul Attributes
    -- Maintenance tracking fields for operational decision-making.
    -- -------------------------------------------------------------------------
    MAINTENANCE_CYCLE_DAYS      NUMBER(10, 0),
    LAST_MAINTENANCE_DATE       DATE,
    NEXT_MAINTENANCE_DATE       DATE,
    OVERHAUL_REQUIRED           VARCHAR(10),
    OVERHAUL_INTERVAL_HOURS     NUMBER(10, 0),

    -- -------------------------------------------------------------------------
    -- Hazardous Material and Safety Attributes
    -- Safety classification and handling requirements.
    -- -------------------------------------------------------------------------
    HAZMAT_FLAG                 VARCHAR(10),
    HAZMAT_CLASS                VARCHAR(50),
    SAFETY_RATING               VARCHAR(50),
    HANDLING_INSTRUCTIONS       VARCHAR(500),

    -- -------------------------------------------------------------------------
    -- Documentation and Reference Attributes
    -- Reference numbers and documentation links for traceability.
    -- -------------------------------------------------------------------------
    DRAWING_NUMBER              VARCHAR(100),
    SPECIFICATION_NUMBER        VARCHAR(100),
    REVISION_LEVEL              VARCHAR(20),
    DOCUMENT_REFERENCE          VARCHAR(255),
    PART_MANUAL_URL             VARCHAR(500),

    -- -------------------------------------------------------------------------
    -- Country of Origin and Export Control
    -- Export compliance and country of origin tracking.
    -- -------------------------------------------------------------------------
    COUNTRY_OF_ORIGIN           VARCHAR(100),
    EXPORT_CONTROL_CLASS        VARCHAR(50),
    ITAR_FLAG                   VARCHAR(10),
    EAR_FLAG                    VARCHAR(10),

    -- -------------------------------------------------------------------------
    -- Shelf Life and Storage Attributes
    -- Shelf life and storage condition requirements.
    -- -------------------------------------------------------------------------
    SHELF_LIFE_DAYS             NUMBER(10, 0),
    STORAGE_TEMPERATURE_MIN_C   NUMBER(10, 2),
    STORAGE_TEMPERATURE_MAX_C   NUMBER(10, 2),
    STORAGE_HUMIDITY_MAX_PCT    NUMBER(10, 2),
    STORAGE_CONDITIONS          VARCHAR(255),

    -- -------------------------------------------------------------------------
    -- Traceability and Serial Number Attributes
    -- Serial and lot number tracking for full traceability.
    -- -------------------------------------------------------------------------
    SERIAL_NUMBER               VARCHAR(100),
    LOT_NUMBER                  VARCHAR(100),
    BATCH_NUMBER                VARCHAR(100),
    TRACE_CODE                  VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Cost and Financial Attributes
    -- Additional cost tracking fields for procurement analysis.
    -- -------------------------------------------------------------------------
    STANDARD_COST_USD           NUMBER(18, 6),
    LAST_PURCHASE_PRICE_USD     NUMBER(18, 6),
    AVERAGE_COST_USD            NUMBER(18, 6),
    REPLACEMENT_COST_USD        NUMBER(18, 6),

    -- -------------------------------------------------------------------------
    -- Program and Project Association
    -- Links the part to specific aerospace programs or projects.
    -- -------------------------------------------------------------------------
    PROGRAM_NAME                VARCHAR(255),
    PROJECT_CODE                VARCHAR(100),
    CONTRACT_NUMBER             VARCHAR(100),
    CUSTOMER_NAME               VARCHAR(255),

    -- -------------------------------------------------------------------------
    -- Audit and Metadata Attributes
    -- UPDATED_AT is the primary incremental load filter column per RULE-003.
    -- Records with UPDATED_AT > last_successful_execution_timestamp are
    -- processed in each incremental run. On first run, all records are loaded.
    -- CREATED_AT captures the original record creation timestamp.
    -- -------------------------------------------------------------------------
    CREATED_AT                  TIMESTAMP_NTZ,
    UPDATED_AT                  TIMESTAMP_NTZ,
    CREATED_BY                  VARCHAR(100),
    UPDATED_BY                  VARCHAR(100),
    SOURCE_SYSTEM               VARCHAR(100),
    SOURCE_RECORD_ID            VARCHAR(100),
    LOAD_TIMESTAMP              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- -------------------------------------------------------------------------
    -- Additional Classification Attributes
    -- Extended classification fields for reporting and analytics.
    -- -------------------------------------------------------------------------
    CRITICALITY_LEVEL           VARCHAR(50),
    OBSOLESCENCE_STATUS         VARCHAR(50),
    ALTERNATE_PART_NUMBER       VARCHAR(100),
    SUPERSEDED_BY_PART_NUMBER   VARCHAR(100),
    NATO_STOCK_NUMBER           VARCHAR(50),
    CAGE_CODE                   VARCHAR(20),
    UNIT_OF_MEASURE             VARCHAR(20),
    COMMODITY_CODE              VARCHAR(50),
    TARIFF_CODE                 VARCHAR(50),
    ASSET_CLASS                 VARCHAR(50)

);

-- =============================================================================
-- SECTION 3: TABLE COMMENTS
-- Apply descriptive comments to the table and key columns for documentation
-- and data catalog discoverability.
-- =============================================================================

-- Apply table-level comment describing purpose and role in the pipeline
COMMENT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE IS
    'Staging table for raw aerospace parts inventory data loaded from the upstream source system. '
    'Serves as the input layer for SP_LOAD_AEROSPACE_PARTS_SCD1. No transformations are applied '
    'at this layer. Records are deduplicated, filtered, transformed, and merged into '
    'AEROSPACE_PARTS_TARGET via SCD Type 1 logic. UPDATED_AT is the incremental load key. '
    'Generated By: SDLC_AGENT.';

-- Apply column-level comment on the primary business key
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.PART_NUMBER IS
    'Unique business key for each aerospace part. Used as the merge key in SCD Type 1 processing '
    'and as the deduplication partition key per RULE-002 and DEC-002.';

-- Apply column-level comment on the incremental load timestamp column
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.UPDATED_AT IS
    'Timestamp of the last update to the source record. Used as the incremental load filter '
    'per RULE-003: only records with UPDATED_AT > last_successful_execution_timestamp are '
    'processed in incremental runs. On first run, all records are loaded.';

-- Apply column-level comment on LIFECYCLE_STATUS (used in exclusion rule)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.LIFECYCLE_STATUS IS
    'Current lifecycle status of the aerospace part. Used in RULE-005 exclusion logic: '
    'records where LIFECYCLE_STATUS = End of Life AND INSTALLATION_DATE < 3 years ago are excluded.';

-- Apply column-level comment on INSTALLATION_DATE (used in exclusion rule)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.INSTALLATION_DATE IS
    'Date the part was installed. Used in RULE-005 exclusion logic in conjunction with '
    'LIFECYCLE_STATUS to filter out End of Life records older than 3 years.';

-- Apply column-level comment on CERTIFICATION_STATUS (used in RISK_SCORE derivation)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.CERTIFICATION_STATUS IS
    'Certification status of the aerospace part. Drives RISK_SCORE derivation per RULE-009. '
    'Expected values: Pending, FAA, EASA, Dual. Unexpected values default to Medium Risk.';

-- Apply column-level comment on LEAD_TIME_DAYS (used in RISK_SCORE derivation)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.LEAD_TIME_DAYS IS
    'Procurement lead time in days. Used in RISK_SCORE derivation per RULE-009: '
    'lead_time_days > 90 contributes to High Risk; > 120 contributes to Medium Risk; '
    '<= 60 with valid certification contributes to Low Risk.';

-- Apply column-level comment on MANUFACTURER (subject to CamelCase transformation)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.MANUFACTURER IS
    'Raw manufacturer name as received from the source system. Will be transformed to '
    'CamelCase format in AEROSPACE_PARTS_TARGET per RULE-006.';

-- Apply column-level comment on WEIGHT_KG (subject to null replacement)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.WEIGHT_KG IS
    'Weight of the part in kilograms. NULL or zero values will be replaced with 0.01 '
    'in AEROSPACE_PARTS_TARGET per RULE-007.';

-- Apply column-level comment on UNIT_PRICE_USD (subject to rounding)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.UNIT_PRICE_USD IS
    'Unit price of the part in US dollars. Will be rounded to 2 decimal places in '
    'AEROSPACE_PARTS_TARGET per RULE-008.';

-- Apply column-level comment on LOAD_TIMESTAMP (pipeline metadata)
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.LOAD_TIMESTAMP IS
    'Timestamp when the record was loaded into the staging table. Defaults to CURRENT_TIMESTAMP(). '
    'Used for pipeline auditing and troubleshooting.';

-- =============================================================================
-- END OF FILE: 01_ddl_source_table.sql
-- =============================================================================