-- =============================================================================
-- Object Name   : AEROSPACE_PARTS_SOURCE
-- Purpose       : DDL to create the AEROSPACE_PARTS_SOURCE staging table in
--                 GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD. This table serves as
--                 the landing zone for raw aerospace parts inventory data
--                 ingested from upstream source systems prior to transformation,
--                 deduplication, and loading into the target analytical table.
-- Generated By  : SDLC_AGENT
-- Generated Date: 2025-01-31
-- =============================================================================

-- =============================================================================
-- SECTION 1: DATABASE AND SCHEMA CONTEXT
-- Set the active database and schema context for all subsequent DDL statements.
-- =============================================================================

-- Set active database context to the project database
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set active schema context to the project schema
USE SCHEMA SDLC_WIZARD;

-- =============================================================================
-- SECTION 2: SOURCE STAGING TABLE CREATION
-- Create the AEROSPACE_PARTS_SOURCE staging table if it does not already exist.
-- This table captures all raw inbound records from the source system including
-- part metadata, lifecycle status, certification details, pricing, weight,
-- lead time, and audit timestamps required for incremental load processing.
-- =============================================================================

-- Create the AEROSPACE_PARTS_SOURCE staging table with all required source columns.
-- PART_NUMBER is the natural business key used for deduplication and SCD1 merge.
-- UPDATED_AT drives incremental load watermark logic in the ETL stored procedure.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (

    -- -------------------------------------------------------------------------
    -- Primary Business Key
    -- Unique identifier for each aerospace part in the source system.
    -- Used as the deduplication key and SCD Type 1 merge key downstream.
    -- -------------------------------------------------------------------------
    PART_NUMBER             VARCHAR(100)        NOT NULL,

    -- -------------------------------------------------------------------------
    -- Part Descriptive Attributes
    -- Core descriptive metadata about the aerospace part.
    -- -------------------------------------------------------------------------

    -- Name or description of the aerospace part
    PART_NAME               VARCHAR(255),

    -- Part category or classification (e.g., Structural, Avionics, Propulsion)
    PART_CATEGORY           VARCHAR(100),

    -- Name of the manufacturer; will be transformed via INITCAP in the ETL layer
    MANUFACTURER            VARCHAR(255),

    -- Country where the manufacturer is headquartered or part is produced
    MANUFACTURER_COUNTRY    VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Physical and Financial Attributes
    -- Measurable properties of the part used in transformation and risk scoring.
    -- -------------------------------------------------------------------------

    -- Weight of the part in kilograms; values <= 0 will be nullified in ETL
    WEIGHT_KG               NUMBER(18, 4),

    -- Unit price of the part in US dollars; will be rounded to 2 decimal places
    UNIT_PRICE_USD          NUMBER(18, 2),

    -- Quantity of units currently available in inventory
    QUANTITY_IN_STOCK       NUMBER(18, 0),

    -- Reorder threshold quantity; triggers procurement when stock falls below
    REORDER_THRESHOLD       NUMBER(18, 0),

    -- -------------------------------------------------------------------------
    -- Lifecycle and Installation Attributes
    -- Used for exclusion logic: records with LIFECYCLE_STATUS = 'End of Life'
    -- AND INSTALLATION_DATE older than 3 years are excluded from the target.
    -- -------------------------------------------------------------------------

    -- Current lifecycle status of the part (e.g., Active, End of Life, Obsolete)
    LIFECYCLE_STATUS        VARCHAR(50),

    -- Date the part was first installed or placed into service
    INSTALLATION_DATE       DATE,

    -- Date the part is scheduled for retirement or end of support
    RETIREMENT_DATE         DATE,

    -- -------------------------------------------------------------------------
    -- Certification and Compliance Attributes
    -- Used in RISK_SCORE derivation logic based on certification authority
    -- and whether certification is current, pending, or expired.
    -- -------------------------------------------------------------------------

    -- Certification authority or standard (e.g., FAA, EASA, Dual, Pending, Expired)
    CERTIFICATION_STATUS    VARCHAR(100),

    -- Specific certification identifier or document reference number
    CERTIFICATION_ID        VARCHAR(100),

    -- Date the current certification was issued
    CERTIFICATION_DATE      DATE,

    -- Date the current certification expires; used to detect expired certifications
    CERTIFICATION_EXPIRY    DATE,

    -- -------------------------------------------------------------------------
    -- Procurement and Supply Chain Attributes
    -- Lead time is a key input to RISK_SCORE derivation logic.
    -- -------------------------------------------------------------------------

    -- Number of days required to procure or manufacture the part from order date
    LEAD_TIME_DAYS          NUMBER(10, 0),

    -- Name of the primary supplier for this part
    SUPPLIER_NAME           VARCHAR(255),

    -- Unique identifier for the supplier in the procurement system
    SUPPLIER_ID             VARCHAR(100),

    -- Preferred shipping or delivery method for this part
    SHIPPING_METHOD         VARCHAR(100),

    -- -------------------------------------------------------------------------
    -- Operational and Maintenance Attributes
    -- Additional operational metadata supporting compliance and reporting.
    -- -------------------------------------------------------------------------

    -- Aircraft model or platform this part is compatible with
    AIRCRAFT_MODEL          VARCHAR(255),

    -- Airworthiness Directive reference number if applicable
    AIRWORTHINESS_DIRECTIVE VARCHAR(100),

    -- Maintenance interval in flight hours before inspection or replacement
    MAINTENANCE_INTERVAL_HRS NUMBER(10, 0),

    -- Indicates whether the part is classified as safety-critical (Y/N)
    SAFETY_CRITICAL_FLAG    VARCHAR(1),

    -- Indicates whether the part is subject to export control regulations (Y/N)
    EXPORT_CONTROL_FLAG     VARCHAR(1),

    -- -------------------------------------------------------------------------
    -- Audit and Watermark Columns
    -- UPDATED_AT is the primary watermark column used by the incremental load
    -- logic in SP_LOAD_AEROSPACE_PARTS_SCD1 to identify new or changed records.
    -- -------------------------------------------------------------------------

    -- Timestamp when the record was originally created in the source system
    CREATED_AT              TIMESTAMP_NTZ,

    -- Timestamp when the record was last modified in the source system;
    -- used as the incremental load watermark in the ETL stored procedure
    UPDATED_AT              TIMESTAMP_NTZ,

    -- Source system identifier or feed name for traceability
    SOURCE_SYSTEM           VARCHAR(100),

    -- Batch or load identifier from the upstream extraction process
    SOURCE_BATCH_ID         VARCHAR(100)

);

-- =============================================================================
-- SECTION 3: TABLE COMMENTS
-- Apply descriptive comments to the table and key columns for documentation
-- and data catalog discoverability purposes.
-- =============================================================================

-- Apply a descriptive comment to the AEROSPACE_PARTS_SOURCE table
COMMENT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE IS
    'Staging table for raw aerospace parts inventory data ingested from upstream source systems. '
    'Serves as the input to the SP_LOAD_AEROSPACE_PARTS_SCD1 ETL pipeline. '
    'Records are deduplicated, transformed, and merged into AEROSPACE_PARTS_TARGET daily at 02:00 UTC.';

-- Apply column-level comments for key business and ETL columns
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.PART_NUMBER IS
    'Unique business key identifying each aerospace part. Used as the SCD Type 1 merge key and deduplication key.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.MANUFACTURER IS
    'Raw manufacturer name from source system. Transformed to CamelCase (INITCAP) during ETL load into target.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.WEIGHT_KG IS
    'Part weight in kilograms. Values <= 0 are treated as NULL during ETL transformation.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.UNIT_PRICE_USD IS
    'Unit price in US dollars. Rounded to 2 decimal places during ETL transformation.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.LIFECYCLE_STATUS IS
    'Current lifecycle status of the part. Records with End of Life status and INSTALLATION_DATE older than 3 years are excluded from the target.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.INSTALLATION_DATE IS
    'Date the part was placed into service. Used in conjunction with LIFECYCLE_STATUS for exclusion logic.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.CERTIFICATION_STATUS IS
    'Certification authority or status (e.g., FAA, EASA, Dual, Pending, Expired). Key input to RISK_SCORE derivation.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.LEAD_TIME_DAYS IS
    'Procurement lead time in days. Used in RISK_SCORE derivation: >120 days contributes to Medium Risk; >90 days contributes to High Risk boundary checks.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE.UPDATED_AT IS
    'Timestamp of last modification in the source system. Primary watermark column for incremental load logic in SP_LOAD_AEROSPACE_PARTS_SCD1.';

-- =============================================================================
-- END OF FILE: 01_ddl_source_table.sql
-- =============================================================================