-- ============================================================
-- File Header
-- Object Name  : AEROSPACE_PARTS_TARGET
-- Purpose      : DDL to create the AEROSPACE_PARTS_TARGET table
--                with all source columns plus additional ETL
--                metadata and derived columns (PART_STATUS,
--                RISK_SCORE, ETL_INSERT_TS, ETL_UPDATE_TS).
--                This table serves as the analytics-ready,
--                SCD Type 1 managed target for the Aerospace
--                Parts Inventory Data Integration pipeline.
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-31
-- ============================================================


-- ============================================================
-- SECTION 1: Set Active Database and Schema Context
-- ============================================================

-- Set the active database for all subsequent statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema for all subsequent statements
USE SCHEMA SDLC_WIZARD;


-- ============================================================
-- SECTION 2: Create AEROSPACE_PARTS_TARGET Table
-- ============================================================

-- Create the target table if it does not already exist.
-- This table mirrors all columns from AEROSPACE_PARTS_SOURCE
-- and adds ETL-managed columns:
--   PART_STATUS    : Lifecycle/soft-delete status managed by ETL
--   RISK_SCORE     : Derived compliance risk classification
--   ETL_INSERT_TS  : Timestamp when the record was first inserted
--   ETL_UPDATE_TS  : Timestamp when the record was last updated
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (

    -- --------------------------------------------------------
    -- Business Key
    -- --------------------------------------------------------
    -- Unique identifier for each aerospace part (natural key)
    PART_NUMBER             VARCHAR(100)        NOT NULL,

    -- --------------------------------------------------------
    -- Core Descriptive Columns (mirrored from source)
    -- --------------------------------------------------------
    -- Manufacturer name; stored in CamelCase (INITCAP applied by ETL)
    MANUFACTURER            VARCHAR(255),

    -- Part description or name
    PART_NAME               VARCHAR(500),

    -- Part category or classification
    PART_CATEGORY           VARCHAR(100),

    -- Weight in kilograms; NULL when source value is <= 0
    WEIGHT_KG               NUMBER(18, 4),

    -- Unit price in USD; rounded to 2 decimal places by ETL
    UNIT_PRICE_USD          NUMBER(18, 2),

    -- Current quantity available in inventory
    QUANTITY_ON_HAND        NUMBER(18, 0),

    -- Reorder threshold quantity
    REORDER_LEVEL           NUMBER(18, 0),

    -- Warehouse or storage location identifier
    WAREHOUSE_LOCATION      VARCHAR(200),

    -- --------------------------------------------------------
    -- Lifecycle and Compliance Columns
    -- --------------------------------------------------------
    -- Lifecycle status of the part (e.g., Active, End of Life)
    LIFECYCLE_STATUS        VARCHAR(100),

    -- Date the part was installed or first put into service
    INSTALLATION_DATE       DATE,

    -- Certification authority status (e.g., FAA, EASA, Dual, Pending)
    CERTIFICATION_STATUS    VARCHAR(100),

    -- Lead time in days to procure or manufacture the part
    LEAD_TIME_DAYS          NUMBER(10, 0),

    -- Supplier or vendor name
    SUPPLIER_NAME           VARCHAR(255),

    -- Country of origin for the part
    COUNTRY_OF_ORIGIN       VARCHAR(100),

    -- Compliance flag indicating regulatory adherence
    COMPLIANCE_FLAG         VARCHAR(50),

    -- --------------------------------------------------------
    -- Timestamp Columns (mirrored from source)
    -- --------------------------------------------------------
    -- Timestamp of the last update in the source system
    UPDATED_AT              TIMESTAMP_NTZ,

    -- Timestamp when the record was originally created in source
    CREATED_AT              TIMESTAMP_NTZ,

    -- --------------------------------------------------------
    -- ETL-Derived and Managed Columns
    -- --------------------------------------------------------
    -- Part status managed by the ETL pipeline.
    -- Values: 'Active' for live records,
    --         'Decommissioned' for soft-deleted records
    --         absent from the source in an incremental run.
    PART_STATUS             VARCHAR(50),

    -- Derived risk classification based on CERTIFICATION_STATUS
    -- and LEAD_TIME_DAYS.
    -- Values:
    --   'High Risk'   : CERTIFICATION_STATUS NOT IN ('FAA','EASA','Dual')
    --                   AND LEAD_TIME_DAYS > 90
    --   'Medium Risk' : CERTIFICATION_STATUS = 'Pending'
    --                   OR LEAD_TIME_DAYS > 120
    --   'Low Risk'    : CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
    --                   AND LEAD_TIME_DAYS <= 90
    --   'Unclassified': All other combinations
    RISK_SCORE              VARCHAR(50),

    -- Timestamp when this record was first inserted into the target
    ETL_INSERT_TS           TIMESTAMP_NTZ,

    -- Timestamp when this record was last updated by the ETL pipeline
    ETL_UPDATE_TS           TIMESTAMP_NTZ,

    -- --------------------------------------------------------
    -- Primary Key Constraint
    -- --------------------------------------------------------
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)

);


-- ============================================================
-- SECTION 3: Add Table and Column Comments
-- ============================================================

-- Add a descriptive comment to the target table
COMMENT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET IS
    'Analytics-ready SCD Type 1 target table for Aerospace Parts Inventory. '
    'Populated daily by SP_LOAD_AEROSPACE_PARTS_SCD1. Includes all source '
    'columns plus ETL-managed PART_STATUS, derived RISK_SCORE, and audit '
    'timestamps ETL_INSERT_TS and ETL_UPDATE_TS.';

-- Column-level comments for documentation and data lineage
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.PART_NUMBER IS
    'Unique business key for each aerospace part. Used as the SCD Type 1 merge key.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.MANUFACTURER IS
    'Manufacturer name transformed to CamelCase (INITCAP) by the ETL pipeline.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.PART_NAME IS
    'Descriptive name or title of the aerospace part.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.PART_CATEGORY IS
    'Category or classification grouping for the aerospace part.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.WEIGHT_KG IS
    'Weight of the part in kilograms. Set to NULL by ETL when source value is <= 0.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.UNIT_PRICE_USD IS
    'Unit price in US dollars. Rounded to 2 decimal places by the ETL pipeline.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.QUANTITY_ON_HAND IS
    'Current quantity of the part available in inventory.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.REORDER_LEVEL IS
    'Minimum quantity threshold that triggers a reorder for this part.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.WAREHOUSE_LOCATION IS
    'Physical warehouse or bin location where the part is stored.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.LIFECYCLE_STATUS IS
    'Current lifecycle stage of the part (e.g., Active, End of Life, Obsolete).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.INSTALLATION_DATE IS
    'Date the part was installed or first placed into operational service.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.CERTIFICATION_STATUS IS
    'Regulatory certification authority for the part (e.g., FAA, EASA, Dual, Pending, None).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.LEAD_TIME_DAYS IS
    'Number of days required to procure or manufacture the part from the supplier.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.SUPPLIER_NAME IS
    'Name of the primary supplier or vendor for this aerospace part.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.COUNTRY_OF_ORIGIN IS
    'Country where the part is manufactured or sourced from.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.COMPLIANCE_FLAG IS
    'Indicator of whether the part meets applicable regulatory compliance requirements.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.UPDATED_AT IS
    'Timestamp of the most recent update to this record in the source system.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.CREATED_AT IS
    'Timestamp when the record was originally created in the source system.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.PART_STATUS IS
    'ETL-managed status flag. Active = present in source; Decommissioned = soft-deleted by ETL.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.RISK_SCORE IS
    'Derived risk classification: High Risk, Medium Risk, Low Risk, or Unclassified. '
    'Based on CERTIFICATION_STATUS and LEAD_TIME_DAYS per BRD risk scoring rules.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.ETL_INSERT_TS IS
    'Timestamp when this record was first inserted into AEROSPACE_PARTS_TARGET by the ETL pipeline.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET.ETL_UPDATE_TS IS
    'Timestamp when this record was last updated in AEROSPACE_PARTS_TARGET by the ETL pipeline.';