-- ============================================================
-- File Header
-- Object Name  : ETL_RECONCILIATION_LOG
-- Purpose      : DDL to create the ETL_RECONCILIATION_LOG table
--                for pipeline run tracking in the Aerospace Parts
--                Inventory Data Integration project. Each pipeline
--                execution writes one row capturing insert, update,
--                decommission, exclusion, and total-processed counts
--                together with a final pipeline status indicator.
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-31
-- ============================================================

-- ============================================================
-- Section 1: Database and Schema Context
-- ============================================================

-- Set the active database and schema so all subsequent DDL
-- statements resolve to the correct namespace without requiring
-- fully-qualified identifiers on every object.
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- ============================================================
-- Section 2: Create ETL_RECONCILIATION_LOG Table
-- ============================================================

-- Create the ETL_RECONCILIATION_LOG table if it does not already
-- exist. This table stores one audit row per pipeline execution of
-- SP_LOAD_AEROSPACE_PARTS_SCD1, enabling full traceability of every
-- run including record-level counts and final pipeline status.
--
-- Column descriptions:
--   RUN_ID               - Surrogate primary key; auto-incremented
--                          sequence value assigned at insert time.
--   RUN_TIMESTAMP        - Wall-clock UTC timestamp recorded at the
--                          moment the pipeline run begins.
--   PIPELINE_START_TS    - Explicit start timestamp of the stored
--                          procedure execution (TIMESTAMP_NTZ).
--   PIPELINE_END_TS      - Explicit end timestamp recorded just
--                          before the procedure returns.
--   SOURCE_ROW_COUNT     - Total rows present in the source staging
--                          table before any filtering or dedup.
--   INCREMENTAL_ROW_COUNT- Rows selected after applying the
--                          incremental UPDATED_AT filter (or all
--                          rows on first run).
--   RECORDS_DEDUPLICATED - Number of duplicate rows removed during
--                          the deduplication step (source rows minus
--                          distinct PART_NUMBER rows).
--   RECORDS_EXCLUDED     - Rows dropped by the exclusion rule
--                          (LIFECYCLE_STATUS = 'End of Life' AND
--                          INSTALLATION_DATE < 3 years ago).
--   RECORDS_INSERTED     - Net new PART_NUMBER rows inserted into
--                          AEROSPACE_PARTS_TARGET by the MERGE.
--   RECORDS_UPDATED      - Existing PART_NUMBER rows updated in
--                          AEROSPACE_PARTS_TARGET by the MERGE.
--   RECORDS_DECOMMISSIONED - Target rows soft-deleted (PART_STATUS
--                          set to 'Decommissioned') because the
--                          PART_NUMBER was absent from the current
--                          source extract.
--   TOTAL_PROCESSED      - Sum of RECORDS_INSERTED + RECORDS_UPDATED
--                          + RECORDS_DECOMMISSIONED; represents the
--                          total rows touched in the target table
--                          during this run.
--   LAST_SUCCESSFUL_RUN_TS - The high-watermark UPDATED_AT timestamp
--                          used as the lower bound for the next
--                          incremental load. Populated only when
--                          PIPELINE_STATUS = 'SUCCESS'.
--   PIPELINE_STATUS      - Final outcome of the run:
--                          'SUCCESS', 'PARTIAL', or 'FAILED'.
--   ERROR_MESSAGE        - Populated with SQLERRM text when the
--                          pipeline encounters an unhandled exception;
--                          NULL on successful runs.
--   CREATED_BY           - Name of the stored procedure or user
--                          session that inserted this log row.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (

    -- Surrogate primary key; auto-incremented by Snowflake sequence
    -- assigned via DEFAULT in the stored procedure INSERT statement.
    RUN_ID                  NUMBER          NOT NULL,

    -- UTC wall-clock timestamp at the moment the log row is written.
    RUN_TIMESTAMP           TIMESTAMP_NTZ   NOT NULL
                                DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()),

    -- Explicit start and end timestamps for duration measurement.
    PIPELINE_START_TS       TIMESTAMP_NTZ   NULL,
    PIPELINE_END_TS         TIMESTAMP_NTZ   NULL,

    -- Row-count metrics captured at each stage of the pipeline.
    SOURCE_ROW_COUNT        NUMBER          NOT NULL DEFAULT 0,
    INCREMENTAL_ROW_COUNT   NUMBER          NOT NULL DEFAULT 0,
    RECORDS_DEDUPLICATED    NUMBER          NOT NULL DEFAULT 0,
    RECORDS_EXCLUDED        NUMBER          NOT NULL DEFAULT 0,

    -- MERGE outcome counts written after the SCD1 MERGE statement.
    RECORDS_INSERTED        NUMBER          NOT NULL DEFAULT 0,
    RECORDS_UPDATED         NUMBER          NOT NULL DEFAULT 0,

    -- Soft-delete count written after the Decommission UPDATE step.
    RECORDS_DECOMMISSIONED  NUMBER          NOT NULL DEFAULT 0,

    -- Derived total: RECORDS_INSERTED + RECORDS_UPDATED
    --                + RECORDS_DECOMMISSIONED.
    TOTAL_PROCESSED         NUMBER          NOT NULL DEFAULT 0,

    -- High-watermark timestamp used as the incremental lower bound
    -- for the next pipeline run; NULL when the run failed.
    LAST_SUCCESSFUL_RUN_TS  TIMESTAMP_NTZ   NULL,

    -- Final pipeline status indicator.
    -- Allowed values: 'SUCCESS', 'PARTIAL', 'FAILED'.
    PIPELINE_STATUS         VARCHAR(20)     NOT NULL,

    -- Error detail captured from SQLERRM on exception; NULL on success.
    ERROR_MESSAGE           VARCHAR(4000)   NULL,

    -- Audit column: name of the calling procedure or session user.
    CREATED_BY              VARCHAR(255)    NULL
                                DEFAULT CURRENT_USER()

);

-- ============================================================
-- Section 3: Primary Key Constraint on ETL_RECONCILIATION_LOG
-- ============================================================

-- Add a primary key constraint on RUN_ID to enforce uniqueness of
-- each pipeline run log entry and to support efficient point-lookup
-- queries by run identifier.
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    ADD CONSTRAINT PK_ETL_RECONCILIATION_LOG PRIMARY KEY (RUN_ID);

-- ============================================================
-- Section 4: Sequence for RUN_ID Auto-Increment
-- ============================================================

-- Create a dedicated Snowflake sequence to generate monotonically
-- increasing RUN_ID values. The stored procedure SP_LOAD_AEROSPACE_
-- PARTS_SCD1 will call NEXTVAL on this sequence when inserting each
-- new reconciliation log row, ensuring no two runs share the same
-- RUN_ID even under concurrent execution scenarios.
CREATE SEQUENCE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SEQ_ETL_RECONCILIATION_LOG_RUN_ID
    START     = 1
    INCREMENT = 1
    COMMENT   = 'Sequence for ETL_RECONCILIATION_LOG.RUN_ID auto-increment';

-- ============================================================
-- Section 5: Table and Column Comments
-- ============================================================

-- Apply a descriptive comment to the table itself so that Snowflake
-- Information Schema and data catalog tools surface meaningful
-- documentation without requiring external metadata stores.
COMMENT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG IS
    'Audit log table for the Aerospace Parts Inventory pipeline. '
    'One row is written per execution of SP_LOAD_AEROSPACE_PARTS_SCD1 '
    'capturing row-count metrics, high-watermark timestamps, pipeline '
    'status, and any error messages for full run traceability.';

-- Column-level comments for self-documenting schema.
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RUN_ID
    IS 'Surrogate primary key; populated from SEQ_ETL_RECONCILIATION_LOG_RUN_ID.NEXTVAL.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RUN_TIMESTAMP
    IS 'UTC timestamp at which the log row was inserted; defaults to CURRENT_TIMESTAMP in UTC.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.PIPELINE_START_TS
    IS 'UTC timestamp recorded at the beginning of the stored procedure execution.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.PIPELINE_END_TS
    IS 'UTC timestamp recorded just before the stored procedure returns.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.SOURCE_ROW_COUNT
    IS 'Total rows in AEROSPACE_PARTS_SOURCE before any filtering.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.INCREMENTAL_ROW_COUNT
    IS 'Rows selected after applying the UPDATED_AT incremental filter (all rows on first run).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECORDS_DEDUPLICATED
    IS 'Number of duplicate rows removed: INCREMENTAL_ROW_COUNT minus distinct PART_NUMBER count.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECORDS_EXCLUDED
    IS 'Rows dropped by exclusion rule: LIFECYCLE_STATUS=End of Life AND INSTALLATION_DATE older than 3 years.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECORDS_INSERTED
    IS 'Net new PART_NUMBER rows inserted into AEROSPACE_PARTS_TARGET by the SCD1 MERGE.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECORDS_UPDATED
    IS 'Existing PART_NUMBER rows updated in AEROSPACE_PARTS_TARGET by the SCD1 MERGE.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECORDS_DECOMMISSIONED
    IS 'Target rows soft-deleted (PART_STATUS=Decommissioned) because PART_NUMBER was absent from source.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.TOTAL_PROCESSED
    IS 'RECORDS_INSERTED + RECORDS_UPDATED + RECORDS_DECOMMISSIONED; total rows touched in target.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.LAST_SUCCESSFUL_RUN_TS
    IS 'High-watermark UPDATED_AT used as lower bound for next incremental load; NULL on failure.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.PIPELINE_STATUS
    IS 'Final run outcome: SUCCESS, PARTIAL, or FAILED.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.ERROR_MESSAGE
    IS 'SQLERRM text captured on unhandled exception; NULL on successful runs.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.CREATED_BY
    IS 'Name of the stored procedure or Snowflake user session that inserted this log row.';