-- =============================================================================
-- Object Name   : ETL_RECONCILIATION_LOG
-- Purpose       : DDL for ETL_RECONCILIATION_LOG table to store per-run audit
--                 counts and metadata for the AEROSPACE_PARTS pipeline.
--                 This table captures source_count, target_count,
--                 inserted_count, updated_count, decommissioned_count,
--                 exclusion_count, run_timestamp, and additional diagnostic
--                 metadata after every execution of SP_LOAD_AEROSPACE_PARTS_SCD1.
--                 Mandatory reconciliation logging is required per RULE-010.
-- Generated By  : SDLC_AGENT
-- Generated Date: 2025-01-31
-- Database      : GEN_AI_POC_SNOWFLAKECOE
-- Schema        : SDLC_WIZARD
-- =============================================================================

-- =============================================================================
-- SECTION 1: USE DATABASE AND SCHEMA CONTEXT
-- =============================================================================

-- Set the active database context for all subsequent statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema context for all subsequent statements
USE SCHEMA SDLC_WIZARD;

-- =============================================================================
-- SECTION 2: CREATE ETL_RECONCILIATION_LOG TABLE
-- =============================================================================

-- Create the ETL_RECONCILIATION_LOG table if it does not already exist.
-- This table stores one row per pipeline execution of SP_LOAD_AEROSPACE_PARTS_SCD1.
-- It captures all audit counts and metadata required by RULE-010 and the
-- mandatory reconciliation requirement defined in the BRD.
-- Columns:
--   RECONCILIATION_ID       : Surrogate primary key, auto-incremented sequence.
--   RUN_ID                  : Unique identifier for each pipeline execution run
--                             (UUID or generated string passed by the procedure).
--   PROCEDURE_NAME          : Name of the stored procedure that generated this log entry.
--   RUN_TIMESTAMP           : UTC timestamp when the pipeline execution started.
--   RUN_END_TIMESTAMP       : UTC timestamp when the pipeline execution completed.
--   LOAD_TYPE               : Indicates whether the run was a FULL load or INCREMENTAL load.
--   INCREMENTAL_FROM_TS     : The last_successful_execution_timestamp used as the
--                             lower bound for incremental filtering (NULL for full load).
--   SOURCE_COUNT            : Total number of records read from AEROSPACE_PARTS_SOURCE
--                             for this run (before deduplication and exclusion).
--   DEDUP_COUNT             : Number of records remaining after deduplication
--                             (latest UPDATED_AT per PART_NUMBER).
--   EXCLUSION_COUNT         : Number of records excluded by RULE-005
--                             (LIFECYCLE_STATUS = End of Life AND INSTALLATION_DATE < 3 years ago).
--   ELIGIBLE_COUNT          : Number of records eligible for merge after dedup and exclusion.
--   INSERTED_COUNT          : Number of net-new records inserted into AEROSPACE_PARTS_TARGET.
--   UPDATED_COUNT           : Number of existing records updated in AEROSPACE_PARTS_TARGET
--                             via SCD Type 1 overwrite.
--   DECOMMISSIONED_COUNT    : Number of records soft-deleted (status set to Decommissioned)
--                             in AEROSPACE_PARTS_TARGET per RULE-004.
--   TARGET_COUNT_BEFORE     : Total record count in AEROSPACE_PARTS_TARGET before this run.
--   TARGET_COUNT_AFTER      : Total record count in AEROSPACE_PARTS_TARGET after this run.
--   HIGH_RISK_COUNT         : Number of records classified as High Risk in this run.
--   MEDIUM_RISK_COUNT       : Number of records classified as Medium Risk in this run.
--   LOW_RISK_COUNT          : Number of records classified as Low Risk in this run.
--   ANOMALOUS_CERT_COUNT    : Number of records with unexpected/unrecognized
--                             CERTIFICATION_STATUS values (supports R-001 mitigation).
--   NULL_WEIGHT_REPLACED    : Number of records where WEIGHT_KG was NULL or <= 0
--                             and was replaced with the default value per RULE-007.
--   PRICE_ROUNDED_COUNT     : Number of records where UNIT_PRICE_USD was rounded
--                             to 2 decimal places per RULE-008.
--   PIPELINE_STATUS         : Overall status of the pipeline run: SUCCESS, FAILURE, PARTIAL.
--   ERROR_MESSAGE           : Error message captured if the pipeline encountered an exception.
--                             NULL when PIPELINE_STATUS = SUCCESS.
--   EXECUTION_DURATION_SEC  : Total execution duration in seconds for the pipeline run.
--   WAREHOUSE_NAME          : Name of the Snowflake virtual warehouse used for this run.
--   CREATED_AT              : Metadata timestamp when this log record was inserted.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (

    -- Surrogate primary key: auto-incremented identity column
    RECONCILIATION_ID         NUMBER          AUTOINCREMENT PRIMARY KEY,

    -- Unique run identifier assigned by the stored procedure per execution
    RUN_ID                    VARCHAR(100)    NOT NULL,

    -- Name of the stored procedure that generated this reconciliation entry
    PROCEDURE_NAME            VARCHAR(200)    NOT NULL,

    -- UTC timestamp marking the start of the pipeline execution
    RUN_TIMESTAMP             TIMESTAMP_NTZ   NOT NULL,

    -- UTC timestamp marking the end of the pipeline execution
    RUN_END_TIMESTAMP         TIMESTAMP_NTZ,

    -- Load type: FULL (first run, no prior control record) or INCREMENTAL
    LOAD_TYPE                 VARCHAR(20)     NOT NULL,

    -- Lower bound timestamp used for incremental filtering (NULL for full load)
    INCREMENTAL_FROM_TS       TIMESTAMP_NTZ,

    -- Total records read from AEROSPACE_PARTS_SOURCE before any filtering
    SOURCE_COUNT              NUMBER          NOT NULL DEFAULT 0,

    -- Records remaining after deduplication (latest UPDATED_AT per PART_NUMBER)
    DEDUP_COUNT               NUMBER          NOT NULL DEFAULT 0,

    -- Records excluded by RULE-005 (End of Life AND INSTALLATION_DATE > 3 years old)
    EXCLUSION_COUNT           NUMBER          NOT NULL DEFAULT 0,

    -- Records eligible for merge after deduplication and exclusion applied
    ELIGIBLE_COUNT            NUMBER          NOT NULL DEFAULT 0,

    -- Net-new records inserted into AEROSPACE_PARTS_TARGET during this run
    INSERTED_COUNT            NUMBER          NOT NULL DEFAULT 0,

    -- Existing records updated (SCD Type 1 overwrite) in AEROSPACE_PARTS_TARGET
    UPDATED_COUNT             NUMBER          NOT NULL DEFAULT 0,

    -- Records soft-deleted (LIFECYCLE_STATUS set to Decommissioned) per RULE-004
    DECOMMISSIONED_COUNT      NUMBER          NOT NULL DEFAULT 0,

    -- Total record count in AEROSPACE_PARTS_TARGET before this pipeline run
    TARGET_COUNT_BEFORE       NUMBER          NOT NULL DEFAULT 0,

    -- Total record count in AEROSPACE_PARTS_TARGET after this pipeline run
    TARGET_COUNT_AFTER        NUMBER          NOT NULL DEFAULT 0,

    -- Count of records classified as High Risk per RULE-009
    HIGH_RISK_COUNT           NUMBER          NOT NULL DEFAULT 0,

    -- Count of records classified as Medium Risk per RULE-009
    MEDIUM_RISK_COUNT         NUMBER          NOT NULL DEFAULT 0,

    -- Count of records classified as Low Risk per RULE-009
    LOW_RISK_COUNT            NUMBER          NOT NULL DEFAULT 0,

    -- Count of records with unrecognized CERTIFICATION_STATUS values (R-001 mitigation)
    ANOMALOUS_CERT_COUNT      NUMBER          NOT NULL DEFAULT 0,

    -- Count of records where WEIGHT_KG was NULL or <= 0 and replaced per RULE-007
    NULL_WEIGHT_REPLACED      NUMBER          NOT NULL DEFAULT 0,

    -- Count of records where UNIT_PRICE_USD was rounded to 2 decimal places per RULE-008
    PRICE_ROUNDED_COUNT       NUMBER          NOT NULL DEFAULT 0,

    -- Overall pipeline run status: SUCCESS, FAILURE, or PARTIAL
    PIPELINE_STATUS           VARCHAR(20)     NOT NULL,

    -- Error message if the pipeline encountered an exception; NULL on success
    ERROR_MESSAGE             VARCHAR(4000),

    -- Total wall-clock execution duration in seconds for the pipeline run
    EXECUTION_DURATION_SEC    NUMBER(10, 2),

    -- Name of the Snowflake virtual warehouse used during this pipeline run
    WAREHOUSE_NAME            VARCHAR(200),

    -- Metadata: UTC timestamp when this reconciliation log record was inserted
    CREATED_AT                TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP()

);

-- =============================================================================
-- SECTION 3: ADD TABLE AND COLUMN COMMENTS FOR DOCUMENTATION
-- =============================================================================

-- Add a descriptive comment to the ETL_RECONCILIATION_LOG table
COMMENT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG IS
    'Stores per-run audit counts and metadata for every execution of SP_LOAD_AEROSPACE_PARTS_SCD1. '
    'Mandatory reconciliation logging per RULE-010 in the Aerospace Parts Pipeline BRD. '
    'One row is inserted per pipeline run capturing source, dedup, exclusion, insert, update, '
    'decommission, and risk classification counts along with pipeline status and error details.';

-- Add column-level comments for key audit and diagnostic columns
COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RECONCILIATION_ID IS
    'Auto-incremented surrogate primary key uniquely identifying each reconciliation log entry.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RUN_ID IS
    'Unique identifier assigned by SP_LOAD_AEROSPACE_PARTS_SCD1 for each pipeline execution. '
    'Used to correlate reconciliation log entries with ETL_CONTROL_LOG entries.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.PROCEDURE_NAME IS
    'Name of the stored procedure that generated this reconciliation log entry. '
    'Expected value: SP_LOAD_AEROSPACE_PARTS_SCD1.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RUN_TIMESTAMP IS
    'UTC timestamp marking the start of the pipeline execution for this run.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.RUN_END_TIMESTAMP IS
    'UTC timestamp marking the completion of the pipeline execution for this run.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.LOAD_TYPE IS
    'Indicates whether this run was a FULL load (first run, no prior control record) '
    'or an INCREMENTAL load (subsequent runs using UPDATED_AT filter per RULE-003).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.INCREMENTAL_FROM_TS IS
    'The last_successful_execution_timestamp value used as the lower bound for incremental '
    'filtering. NULL when LOAD_TYPE = FULL (first run).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.SOURCE_COUNT IS
    'Total number of records read from AEROSPACE_PARTS_SOURCE for this run, '
    'before deduplication or exclusion filtering is applied.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.DEDUP_COUNT IS
    'Number of records remaining after deduplication using ROW_NUMBER() OVER '
    '(PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) per RULE-002.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.EXCLUSION_COUNT IS
    'Number of records excluded by RULE-005: LIFECYCLE_STATUS = End of Life '
    'AND INSTALLATION_DATE is older than 3 years from the current run date.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.ELIGIBLE_COUNT IS
    'Number of records eligible for the SCD Type 1 MERGE after deduplication '
    'and exclusion rules have been applied.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.INSERTED_COUNT IS
    'Number of net-new PART_NUMBER records inserted into AEROSPACE_PARTS_TARGET '
    'during the MERGE operation for this run.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.UPDATED_COUNT IS
    'Number of existing PART_NUMBER records updated (SCD Type 1 overwrite) '
    'in AEROSPACE_PARTS_TARGET during the MERGE operation for this run.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.DECOMMISSIONED_COUNT IS
    'Number of records soft-deleted per RULE-004: PART_NUMBERs present in '
    'AEROSPACE_PARTS_TARGET but absent from the current source extract, '
    'with LIFECYCLE_STATUS set to Decommissioned.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.TARGET_COUNT_BEFORE IS
    'Total record count in AEROSPACE_PARTS_TARGET captured before this pipeline run begins.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.TARGET_COUNT_AFTER IS
    'Total record count in AEROSPACE_PARTS_TARGET captured after this pipeline run completes.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.HIGH_RISK_COUNT IS
    'Count of records classified as High Risk per RULE-009: '
    'DAYS_SINCE_LAST_INSPECTION > 90.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.MEDIUM_RISK_COUNT IS
    'Count of records classified as Medium Risk per RULE-009: '
    'CERTIFICATION_STATUS = Pending OR LEAD_TIME_DAYS > 120 '
    '(and not already classified as High Risk).';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.LOW_RISK_COUNT IS
    'Count of records classified as Low Risk per RULE-009: '
    'CERTIFICATION_STATUS IN (FAA, EASA, Dual) AND LEAD_TIME_DAYS <= 60.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.ANOMALOUS_CERT_COUNT IS
    'Count of records with CERTIFICATION_STATUS values outside the expected set '
    '(Pending, FAA, EASA, Dual). Supports R-001 risk mitigation and anomaly detection.';

COMMENT ON COLUMN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG.NULL_WEIGHT_REPLACED IS
    'Count of records where WEIGHT_KG was NULL or <= 0 and was

---

### FILE: 05_stored_procedure_sp_load_aerospace_parts_scd1.sql ###