-- ============================================================
-- File Header
-- Object Name  : 04_sample_data_source.sql
-- Purpose      : INSERT statements to load sample aerospace parts
--                test data into AEROSPACE_PARTS_SOURCE covering
--                all transformation and RISK_SCORE scenarios,
--                deduplication, exclusion, soft-delete, and
--                idempotency acceptance-criteria test cases.
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-01
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- ============================================================

-- ============================================================
-- SECTION 1: Set Session Context
-- ============================================================

-- Set the active database and schema for all subsequent statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- ============================================================
-- SECTION 2: Truncate Source Table Before Loading Sample Data
-- ============================================================

-- Clear any previously loaded sample data to ensure idempotent test runs
TRUNCATE TABLE AEROSPACE_PARTS_SOURCE;

-- ============================================================
-- SECTION 3: Insert Sample Data — RISK_SCORE Scenario Coverage
--
-- RISK_SCORE derivation rules (from BRD):
--   HIGH   : CERTIFICATION_STATUS NOT IN ('FAA','EASA','Dual')
--             AND LEAD_TIME_DAYS > 90
--   MEDIUM : CERTIFICATION_STATUS = 'Pending'
--             OR LEAD_TIME_DAYS > 120
--   LOW    : CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
--             AND LEAD_TIME_DAYS <= 120
--
-- Exclusion rule:
--   LIFECYCLE_STATUS = 'End of Life' AND INSTALLATION_DATE < DATEADD(year,-3,CURRENT_DATE())
--
-- Deduplication rule:
--   Retain latest record per PART_NUMBER by UPDATED_AT
--
-- Soft-delete rule:
--   Records present in target but absent from source incremental
--   window are marked PART_STATUS = 'Decommissioned'
-- ============================================================

-- ------------------------------------------------------------
-- 3.1  LOW RISK records
--      CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
--      AND LEAD_TIME_DAYS <= 120
-- ------------------------------------------------------------

-- LOW RISK — FAA certified, lead time well within 120 days
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-1001',
    'boeing',                          -- lowercase to test INITCAP transform
    'Hydraulic Pump Assembly',
    'Hydraulics',
    12.50,
    4500.00,
    'Active',
    '2022-06-15',
    'FAA',
    60,
    150,
    30,
    'SUP-001',
    'USA',
    '2024-03-01 08:00:00'::TIMESTAMP_NTZ
);

-- LOW RISK — EASA certified, lead time exactly 120 days (boundary)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-1002',
    'airbus INDUSTRIES',               -- mixed case to test INITCAP transform
    'Landing Gear Strut',
    'Landing Gear',
    85.00,
    22000.00,
    'Active',
    '2023-01-10',
    'EASA',
    120,
    40,
    10,
    'SUP-002',
    'France',
    '2024-03-05 09:30:00'::TIMESTAMP_NTZ
);

-- LOW RISK — Dual certified, short lead time
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-1003',
    'HONEYWELL aerospace',             -- mixed case to test INITCAP transform
    'Avionics Control Unit',
    'Avionics',
    3.20,
    18750.00,
    'Active',
    '2023-07-22',
    'Dual',
    45,
    200,
    50,
    'SUP-003',
    'USA',
    '2024-03-10 11:00:00'::TIMESTAMP_NTZ
);

-- LOW RISK — FAA certified, lead time = 1 day (minimum boundary)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-1004',
    'GE aviation',                     -- mixed case to test INITCAP transform
    'Turbine Blade Set',
    'Propulsion',
    5.80,
    9800.00,
    'Active',
    '2024-01-05',
    'FAA',
    1,
    500,
    100,
    'SUP-004',
    'USA',
    '2024-04-01 07:00:00'::TIMESTAMP_NTZ
);

-- LOW RISK — EASA certified, lead time = 90 days
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-1005',
    'safran',
    'Fuel Flow Control Valve',
    'Fuel Systems',
    2.10,
    3200.00,
    'Active',
    '2023-11-30',
    'EASA',
    90,
    75,
    20,
    'SUP-005',
    'France',
    '2024-04-02 10:15:00'::TIMESTAMP_NTZ
);

-- ------------------------------------------------------------
-- 3.2  MEDIUM RISK records
--      CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
-- ------------------------------------------------------------

-- MEDIUM RISK — Certification is Pending (regardless of lead time)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-2001',
    'raytheon technologies',
    'Radar Antenna Assembly',
    'Avionics',
    14.70,
    55000.00,
    'Active',
    '2024-02-14',
    'Pending',
    60,
    25,
    5,
    'SUP-006',
    'USA',
    '2024-04-05 08:45:00'::TIMESTAMP_NTZ
);

-- MEDIUM RISK — Pending certification AND lead time > 120 (both conditions true)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-2002',
    'THALES group',
    'Flight Management Computer',
    'Avionics',
    8.40,
    72000.00,
    'Active',
    '2024-03-01',
    'Pending',
    150,
    10,
    3,
    'SUP-007',
    'France',
    '2024-04-06 09:00:00'::TIMESTAMP_NTZ
);

-- MEDIUM RISK — FAA certified but lead time > 120 days (lead time override)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-2003',
    'lockheed martin',
    'Composite Wing Panel',
    'Airframe',
    320.00,
    185000.00,
    'Active',
    '2023-05-20',
    'FAA',
    180,
    5,
    2,
    'SUP-008',
    'USA',
    '2024-04-07 14:00:00'::TIMESTAMP_NTZ
);

-- MEDIUM RISK — EASA certified but lead time = 121 days (just above boundary)
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-2004',
    'dassault aviation',
    'Ejection Seat Mechanism',
    'Safety Systems',
    45.00,
    98000.00,
    'Active',
    '2023-09-15',
    'EASA',
    121,
    8,
    2,
    'SUP-009',
    'France',
    '2024-04-08 11:30:00'::TIMESTAMP_NTZ
);

-- MEDIUM RISK — Dual certified but lead time = 200 days
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-2005',
    'rolls royce',
    'Engine Core Module',
    'Propulsion',
    1200.00,
    2500000.00,
    'Active',
    '2022-12-01',
    'Dual',
    200,
    2,
    1,
    'SUP-010',
    'UK',
    '2024-04-09 16:00:00'::TIMESTAMP_NTZ
);

-- ------------------------------------------------------------
-- 3.3  HIGH RISK records
--      CERTIFICATION_STATUS NOT IN ('FAA','EASA','Dual','Pending')
--      AND LEAD_TIME_DAYS > 90
-- ------------------------------------------------------------

-- HIGH RISK — Unknown certification, lead time > 90
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-3001',
    'unknown supplier co',
    'Auxiliary Power Unit',
    'Power Systems',
    95.00,
    42000.00,
    'Active',
    '2023-03-10',
    'Unknown',
    95,
    12,
    4,
    'SUP-011',
    'China',
    '2024-04-10 08:00:00'::TIMESTAMP_NTZ
);

-- HIGH RISK — Expired certification, lead time = 365 days
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SUPPLIER_CODE,
    COUNTRY_OF_ORIGIN,
    UPDATED_AT
)
VALUES (
    'AP-3002',
    'generic parts ltd',
    'Oxygen Generation System',
    'Life Support',
    18.30,
    15000.00,
    'Active',
    '2022-08-20',
    'Expired',
    365,
    6,
    2,
    'SUP-012',
    'India',
    '2024-04-11 09:00:00'::TIMESTAMP_NTZ
);

-- HIGH RISK — No certification (NULL treated as not in approved list), lead time > 90
INSERT INTO AEROSPACE_PARTS_SOURCE (
    PART_NUMBER,
    MANUFACTURER,
    PART_NAME,
    PART_CATEGORY,
    WEIGHT_KG,
    UNIT_PRICE_USD,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    QUANTITY_ON_HAND,
    REORDER_POINT,

---