-- ============================================================
-- Object Name  : SP_LOAD_AEROSPACE_PARTS_SCD1
-- Purpose      : Stored procedure implementing incremental load,
--                deduplication, exclusion, transformation,
--                RISK_SCORE derivation, SCD Type 1 MERGE,
--                soft delete, and reconciliation logging for
--                the Aerospace Parts Inventory pipeline.
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-01
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- ============================================================

-- ============================================================
-- SECTION 1: CREATE OR REPLACE STORED PROCEDURE
-- ============================================================

-- Main stored procedure for SCD Type 1 load of aerospace parts
CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE

    -- --------------------------------------------------------
    -- Variable declarations: run metadata
    -- --------------------------------------------------------
    V_RUN_ID              VARCHAR;
    V_RUN_TIMESTAMP       TIMESTAMP_NTZ;
    V_LAST_RUN_TS         TIMESTAMP_NTZ;
    V_PIPELINE_STATUS     VARCHAR;

    -- --------------------------------------------------------
    -- Variable declarations: record counts
    -- --------------------------------------------------------
    V_RECORDS_INSERTED    NUMBER DEFAULT 0;
    V_RECORDS_UPDATED     NUMBER DEFAULT 0;
    V_RECORDS_DECOMMISSIONED NUMBER DEFAULT 0;
    V_RECORDS_EXCLUDED    NUMBER DEFAULT 0;
    V_TOTAL_PROCESSED     NUMBER DEFAULT 0;

    -- --------------------------------------------------------
    -- Variable declarations: row count holders
    -- --------------------------------------------------------
    V_MERGE_INSERT_COUNT  NUMBER DEFAULT 0;
    V_MERGE_UPDATE_COUNT  NUMBER DEFAULT 0;
    V_SOFT_DELETE_COUNT   NUMBER DEFAULT 0;
    V_EXCL_COUNT          NUMBER DEFAULT 0;
    V_SOURCE_COUNT        NUMBER DEFAULT 0;

    -- --------------------------------------------------------
    -- Variable declarations: result message
    -- --------------------------------------------------------
    V_RESULT_MSG          VARCHAR;

    -- --------------------------------------------------------
    -- SECTION 2: Initialize run metadata
    -- --------------------------------------------------------

    -- Generate a unique run ID using UUID
    V_RUN_ID        := UUID_STRING();
    V_RUN_TIMESTAMP := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    V_PIPELINE_STATUS := 'RUNNING';

    -- --------------------------------------------------------
    -- SECTION 3: Determine last successful run timestamp
    --            for incremental load logic.
    --            If no prior successful run exists, use epoch
    --            (full load scenario).
    -- --------------------------------------------------------

    -- Retrieve the most recent successful run timestamp from the reconciliation log
    LET C_LAST_RUN CURSOR FOR
        SELECT COALESCE(MAX(RUN_TIMESTAMP), '1970-01-01 00:00:00'::TIMESTAMP_NTZ)
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
        WHERE PIPELINE_STATUS = 'SUCCESS';

    OPEN C_LAST_RUN;
    FETCH C_LAST_RUN INTO V_LAST_RUN_TS;
    CLOSE C_LAST_RUN;

    -- --------------------------------------------------------
    -- SECTION 4: Create a temporary staging table to hold
    --            deduplicated, filtered, and transformed
    --            incremental source records for this run.
    -- --------------------------------------------------------

    -- Drop temp table if it exists from a previous failed run
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGING AS
    SELECT
        -- ------------------------------------------------
        -- Deduplication: retain latest record per PART_NUMBER
        -- by UPDATED_AT using ROW_NUMBER + QUALIFY
        -- ------------------------------------------------
        PART_NUMBER,

        -- Transformation: INITCAP on MANUFACTURER
        INITCAP(MANUFACTURER)                                           AS MANUFACTURER,

        -- Transformation: NULL out non-positive WEIGHT_KG
        CASE
            WHEN WEIGHT_KG <= 0 THEN NULL
            ELSE WEIGHT_KG
        END                                                             AS WEIGHT_KG,

        -- Transformation: Round UNIT_PRICE_USD to 2 decimal places
        ROUND(UNIT_PRICE_USD, 2)                                        AS UNIT_PRICE_USD,

        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        UPDATED_AT,

        -- Pass-through columns
        PART_NAME,
        PART_CATEGORY,
        COUNTRY_OF_ORIGIN,
        STOCK_QUANTITY,
        WAREHOUSE_LOCATION,
        LAST_INSPECTION_DATE,
        COMPLIANCE_FLAG,

        -- ------------------------------------------------
        -- RISK_SCORE derivation logic:
        --   High Risk   : certification is NOT in (FAA, EASA, Dual)
        --                 AND lead time > 90 days
        --   Medium Risk : certification is pending
        --                 OR lead time > 120 days
        --   Low Risk    : certification is FAA, EASA, or Dual
        --                 AND lead time <= 90 days
        --   Medium Risk : default fallback
        -- ------------------------------------------------
        CASE
            WHEN CERTIFICATION_STATUS NOT IN ('FAA', 'EASA', 'Dual')
                 AND LEAD_TIME_DAYS > 90
                THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending'
                 OR LEAD_TIME_DAYS > 120
                THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual')
                 AND LEAD_TIME_DAYS <= 90
                THEN 'Low Risk'
            ELSE 'Medium Risk'
        END                                                             AS RISK_SCORE

    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE

    -- --------------------------------------------------------
    -- Incremental filter: only process records updated since
    -- the last successful run (full load when V_LAST_RUN_TS
    -- equals epoch 1970-01-01).
    -- --------------------------------------------------------
    WHERE UPDATED_AT > V_LAST_RUN_TS

    -- --------------------------------------------------------
    -- Exclusion rule: drop records where LIFECYCLE_STATUS is
    -- 'End of Life' AND INSTALLATION_DATE is older than 3 years
    -- --------------------------------------------------------
    AND NOT (
        LIFECYCLE_STATUS = 'End of Life'
        AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
    )

    -- --------------------------------------------------------
    -- Deduplication: keep only the latest record per
    -- PART_NUMBER ordered by UPDATED_AT descending
    -- --------------------------------------------------------
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PART_NUMBER
        ORDER BY UPDATED_AT DESC
    ) = 1;

    -- --------------------------------------------------------
    -- SECTION 5: Capture counts for reconciliation logging
    -- --------------------------------------------------------

    -- Count deduplicated source records entering the merge
    LET C_SRC_COUNT CURSOR FOR
        SELECT COUNT(*) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGING;

    OPEN C_SRC_COUNT;
    FETCH C_SRC_COUNT INTO V_SOURCE_COUNT;
    CLOSE C_SRC_COUNT;

    -- Count excluded records (End of Life AND older than 3 years)
    -- from the full incremental window (before exclusion filter)
    LET C_EXCL CURSOR FOR
        SELECT COUNT(*)
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT > V_LAST_RUN_TS
          AND LIFECYCLE_STATUS = 'End of Life'
          AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

    OPEN C_EXCL;
    FETCH C_EXCL INTO V_EXCL_COUNT;
    CLOSE C_EXCL;

    V_RECORDS_EXCLUDED := V_EXCL_COUNT;

    -- --------------------------------------------------------
    -- SECTION 6: SCD Type 1 MERGE into AEROSPACE_PARTS_TARGET
    --            Business key: PART_NUMBER
    --            On MATCH    : UPDATE all non-key columns
    --            On NOT MATCH: INSERT new record
    -- --------------------------------------------------------

    -- Perform SCD Type 1 MERGE using PART_NUMBER as the business key
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGING    AS SRC
        ON TGT.PART_NUMBER = SRC.PART_NUMBER

    -- When record exists in target: overwrite all attributes (SCD1)
    WHEN MATCHED THEN
        UPDATE SET
            TGT.MANUFACTURER         = SRC.MANUFACTURER,
            TGT.WEIGHT_KG            = SRC.WEIGHT_KG,
            TGT.UNIT_PRICE_USD       = SRC.UNIT_PRICE_USD,
            TGT.LIFECYCLE_STATUS     = SRC.LIFECYCLE_STATUS,
            TGT.INSTALLATION_DATE    = SRC.INSTALLATION_DATE,
            TGT.CERTIFICATION_STATUS = SRC.CERTIFICATION_STATUS,
            TGT.LEAD_TIME_DAYS       = SRC.LEAD_TIME_DAYS,
            TGT.UPDATED_AT           = SRC.UPDATED_AT,
            TGT.PART_NAME            = SRC.PART_NAME,
            TGT.PART_CATEGORY        = SRC.PART_CATEGORY,
            TGT.COUNTRY_OF_ORIGIN    = SRC.COUNTRY_OF_ORIGIN,
            TGT.STOCK_QUANTITY       = SRC.STOCK_QUANTITY,
            TGT.WAREHOUSE_LOCATION   = SRC.WAREHOUSE_LOCATION,
            TGT.LAST_INSPECTION_DATE = SRC.LAST_INSPECTION_DATE,
            TGT.COMPLIANCE_FLAG      = SRC.COMPLIANCE_FLAG,
            TGT.RISK_SCORE           = SRC.RISK_SCORE,
            TGT.PART_STATUS          = 'Active',
            TGT.ETL_UPDATE_TS        = V_RUN_TIMESTAMP

    -- When record is new: insert with ETL metadata
    WHEN NOT MATCHED THEN
        INSERT (
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT,
            PART_NAME,
            PART_CATEGORY,
            COUNTRY_OF_ORIGIN,
            STOCK_QUANTITY,
            WAREHOUSE_LOCATION,
            LAST_INSPECTION_DATE,
            COMPLIANCE_FLAG,
            RISK_SCORE,
            PART_STATUS,
            ETL_INSERT_TS,
            ETL_UPDATE_TS
        )
        VALUES (
            SRC.PART_NUMBER,
            SRC.MANUFACTURER,
            SRC.WEIGHT_KG,
            SRC.UNIT_PRICE_USD,
            SRC.LIFECYCLE_STATUS,
            SRC.INSTALLATION_DATE,
            SRC.CERTIFICATION_STATUS,
            SRC.LEAD_TIME_DAYS,
            SRC.UPDATED_AT,
            SRC.PART_NAME,
            SRC.PART_CATEGORY,
            SRC.COUNTRY_OF_ORIGIN,
            SRC.STOCK_QUANTITY,
            SRC.WAREHOUSE_LOCATION,
            SRC.LAST_INSPECTION_DATE,
            SRC.COMPLIANCE_FLAG,
            SRC.RISK_SCORE,
            'Active',
            V_RUN_TIMESTAMP,
            V_RUN_TIMESTAMP
        );

    -- --------------------------------------------------------
    -- SECTION 7: Capture MERGE insert and update counts
    --            using Snowflake system variable
    -- --------------------------------------------------------

    -- Retrieve row counts from the MERGE statement result
    -- Inserts: records in staging not previously in target
    LET C_MERGE_INS CURSOR FOR
        SELECT COUNT(*)
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
        INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGING SRC
            ON TGT.PART_NUMBER = SRC.PART_NUMBER
        WHERE TGT.ETL_INSERT_TS = V_RUN_TIMESTAMP
          AND TGT.ETL_UPDATE_TS = V_RUN_TIMESTAMP;

    OPEN C_MERGE_INS;
    FETCH C_MERGE_INS INTO V_MERGE_INSERT_COUNT;
    CLOSE C_MERGE_INS;

    -- Updates: records in staging that already existed in target
    -- (updated records have ETL_INSERT_TS < V_RUN_TIMESTAMP but ETL_UPDATE_TS = V_RUN_TIMESTAMP)
    LET C_MERGE_UPD CURSOR FOR
        SELECT COUNT(*)
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
        INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGING SRC
            ON TGT.PART_NUMBER = SRC.PART_NUMBER
        WHERE TGT.ETL_UPDATE_TS = V_RUN_TIMESTAMP
          AND TGT.ETL_INSERT_TS < V_RUN_TIMESTAMP;

    OPEN C_MERGE_UPD;
    FETCH C_MERGE_UPD INTO V_MERGE_UPDATE_COUNT;
    CLOSE C_MERGE_UPD;

    V_RECORDS_INSERTED := V_MERGE_INSERT_COUNT;
    V_RECORDS_UPDATED  := V_MERGE_UPDATE_COUNT;

    -- --------------------------------------------------------
    -- SECTION 8: Soft Delete logic
    --            Records present in AEROSPACE_PARTS_TARGET
    --            with PART_STATUS = 'Active' that are NOT
    --            present in the current full source snapshot
    --            (AEROSPACE_PARTS_SOURCE excluding End of Life
    --            older than 3 years) are marked as
    --            'Decommissioned'.
    --
    --            NOTE: Soft delete applies to the full active
    --            target population vs. the full valid source
    --            population (not just the incremental window),
    --            to correctly identify records removed from
    --            source entirely.
    -- --------------------------------------------------------

    -- Mark active target records absent from valid source as Decommissioned
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
    SET
        TGT.PART_STATUS    = 'Decommissioned',
        TGT.ETL_UPDATE_TS  = V_RUN_TIMESTAMP
    WHERE TGT.PART_STATUS = 'Active'
      AND NOT EXISTS (
          SELECT 1
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE SRC
          WHERE SRC.PART_NUMBER = TGT.PART_NUMBER
            -- Exclude End of Life records older than

---