-- =============================================================================
-- Object Name  : SP_LOAD_AEROSPACE_PARTS_SCD1
-- Purpose      : Stored procedure implementing incremental load, deduplication,
--                SCD Type 1 merge, exclusion rules, soft delete, CamelCase
--                transformation, WEIGHT_KG null replacement, UNIT_PRICE_USD
--                rounding, RISK_SCORE derivation, and reconciliation logging
--                for the AEROSPACE_PARTS pipeline.
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-31
-- =============================================================================

-- =============================================================================
-- SECTION 1: CREATE OR REPLACE STORED PROCEDURE SP_LOAD_AEROSPACE_PARTS_SCD1
-- =============================================================================

-- Main stored procedure implementing all pipeline logic for aerospace parts load
CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    -- -------------------------------------------------------------------------
    -- Variable declarations: control flow, timestamps, and reconciliation counts
    -- -------------------------------------------------------------------------

    -- Last successful execution timestamp retrieved from ETL_CONTROL_LOG
    v_last_run_ts         TIMESTAMP_NTZ DEFAULT NULL;

    -- Flag to determine if this is a full load (first run) or incremental
    v_is_full_load        BOOLEAN       DEFAULT FALSE;

    -- Reconciliation counters
    v_source_count        INTEGER       DEFAULT 0;
    v_target_count_before INTEGER       DEFAULT 0;
    v_inserted_count      INTEGER       DEFAULT 0;
    v_updated_count       INTEGER       DEFAULT 0;
    v_decommissioned_count INTEGER      DEFAULT 0;
    v_exclusion_count     INTEGER       DEFAULT 0;
    v_target_count_after  INTEGER       DEFAULT 0;

    -- Current run timestamp
    v_run_ts              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- Error message holder
    v_error_msg           VARCHAR       DEFAULT '';

    -- Result message
    v_result_msg          VARCHAR       DEFAULT '';

    -- =========================================================================
    -- SECTION 2: RETRIEVE LAST SUCCESSFUL EXECUTION TIMESTAMP
    -- Determine whether this is a full load or incremental load by querying
    -- ETL_CONTROL_LOG for the most recent successful run timestamp.
    -- =========================================================================

    -- Attempt to retrieve the last successful execution timestamp
    LET c_last_run CURSOR FOR
        SELECT LAST_SUCCESSFUL_EXECUTION_TS
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
        WHERE PROCEDURE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1'
          AND STATUS = 'SUCCESS'
        ORDER BY LAST_SUCCESSFUL_EXECUTION_TS DESC
        LIMIT 1;

    OPEN c_last_run;
    FETCH c_last_run INTO v_last_run_ts;
    CLOSE c_last_run;

    -- If no prior successful run exists, perform a full load
    IF (v_last_run_ts IS NULL) THEN
        v_is_full_load := TRUE;
    END IF;

    -- =========================================================================
    -- SECTION 3: CAPTURE TARGET COUNT BEFORE LOAD
    -- Record the number of records in AEROSPACE_PARTS_TARGET before any changes
    -- to support reconciliation reporting.
    -- =========================================================================

    -- Count existing records in target before the load begins
    LET c_target_before CURSOR FOR
        SELECT COUNT(1) AS CNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    OPEN c_target_before;
    FETCH c_target_before INTO v_target_count_before;
    CLOSE c_target_before;

    -- =========================================================================
    -- SECTION 4: CREATE TEMPORARY STAGING TABLE FOR INCREMENTAL SOURCE DATA
    -- Extract records from AEROSPACE_PARTS_SOURCE based on incremental filter
    -- (UPDATED_AT > last run timestamp) or full load if first run.
    -- Apply deduplication using ROW_NUMBER() OVER PARTITION BY PART_NUMBER
    -- ordered by UPDATED_AT DESC to retain the latest record per part.
    -- =========================================================================

    -- Drop temp staging table if it exists from a prior failed run
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_STAGE AS
    SELECT
        PART_NUMBER,
        PART_NAME,
        MANUFACTURER,
        CATEGORY,
        LIFECYCLE_STATUS,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        INSTALLATION_DATE,
        UPDATED_AT,
        CREATED_AT
    FROM (
        SELECT
            SRC.PART_NUMBER,
            SRC.PART_NAME,
            SRC.MANUFACTURER,
            SRC.CATEGORY,
            SRC.LIFECYCLE_STATUS,
            SRC.CERTIFICATION_STATUS,
            SRC.LEAD_TIME_DAYS,
            SRC.WEIGHT_KG,
            SRC.UNIT_PRICE_USD,
            SRC.INSTALLATION_DATE,
            SRC.UPDATED_AT,
            SRC.CREATED_AT,
            -- Deduplication: retain only the latest record per PART_NUMBER
            ROW_NUMBER() OVER (
                PARTITION BY SRC.PART_NUMBER
                ORDER BY SRC.UPDATED_AT DESC
            ) AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE SRC
        WHERE
            -- RULE-003: Incremental load filter; full load if first run
            (v_is_full_load = TRUE OR SRC.UPDATED_AT > v_last_run_ts)
    )
    -- RULE-002: Keep only the most recent record per PART_NUMBER (deduplication)
    QUALIFY RN = 1;

    -- =========================================================================
    -- SECTION 5: COUNT SOURCE RECORDS AFTER DEDUPLICATION
    -- Capture the deduplicated source record count for reconciliation logging.
    -- =========================================================================

    -- Count deduplicated source records for this run
    LET c_source_count CURSOR FOR
        SELECT COUNT(1) AS CNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_STAGE;

    OPEN c_source_count;
    FETCH c_source_count INTO v_source_count;
    CLOSE c_source_count;

    -- =========================================================================
    -- SECTION 6: CREATE TEMPORARY TABLE FOR TRANSFORMED AND FILTERED RECORDS
    -- Apply all transformation rules:
    --   RULE-005: Exclusion of End of Life records with INSTALLATION_DATE < 3 yrs
    --   RULE-006: CamelCase transformation on MANUFACTURER
    --   RULE-007: WEIGHT_KG NULL or <= 0 replaced with 0.01
    --   RULE-008: UNIT_PRICE_USD rounded to 2 decimal places
    --   RULE-009: RISK_SCORE derivation based on CERTIFICATION_STATUS and LEAD_TIME_DAYS
    -- =========================================================================

    -- Count exclusions before creating the transformed temp table
    LET c_exclusion_count CURSOR FOR
        SELECT COUNT(1) AS CNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_STAGE
        WHERE LIFECYCLE_STATUS = 'End of Life'
          AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

    OPEN c_exclusion_count;
    FETCH c_exclusion_count INTO v_exclusion_count;
    CLOSE c_exclusion_count;

    -- Create transformed staging table with all business rules applied
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_TRANSFORMED AS
    SELECT
        PART_NUMBER,
        PART_NAME,

        -- RULE-006: CamelCase transformation on MANUFACTURER
        -- Convert MANUFACTURER to CamelCase: capitalize first letter of each word,
        -- lowercase remaining letters using INITCAP Snowflake function
        INITCAP(MANUFACTURER) AS MANUFACTURER,

        CATEGORY,
        LIFECYCLE_STATUS,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,

        -- RULE-007: Replace WEIGHT_KG NULL or <= 0 with 0.01
        CASE
            WHEN WEIGHT_KG IS NULL OR WEIGHT_KG <= 0 THEN 0.01
            ELSE WEIGHT_KG
        END AS WEIGHT_KG,

        -- RULE-008: Round UNIT_PRICE_USD to 2 decimal places
        ROUND(UNIT_PRICE_USD, 2) AS UNIT_PRICE_USD,

        INSTALLATION_DATE,
        UPDATED_AT,
        CREATED_AT,

        -- RULE-009: RISK_SCORE derivation logic
        -- Priority 1: lead_time_days > 90 → High Risk
        -- Priority 2: certification_status = 'Pending' OR lead_time_days > 120 → Medium Risk
        -- Priority 3: certification_status IN ('FAA','EASA','Dual') AND lead_time_days <= 60 → Low Risk
        -- Default: Medium Risk
        CASE
            WHEN LEAD_TIME_DAYS > 90
                THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
                THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual') AND LEAD_TIME_DAYS <= 60
                THEN 'Low Risk'
            ELSE 'Medium Risk'
        END AS RISK_SCORE

    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_STAGE

    -- RULE-005: Exclude records where LIFECYCLE_STATUS = 'End of Life'
    --           AND INSTALLATION_DATE is older than 3 years
    WHERE NOT (
        LIFECYCLE_STATUS = 'End of Life'
        AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
    );

    -- =========================================================================
    -- SECTION 7: SCD TYPE 1 MERGE INTO AEROSPACE_PARTS_TARGET
    -- Perform MERGE using PART_NUMBER as the business key.
    -- MATCHED: Update all non-key columns (SCD Type 1 overwrite).
    -- NOT MATCHED: Insert new records.
    -- Tracks inserted and updated counts via $action pseudo-column approach
    -- using a pre/post count strategy for compatibility.
    -- =========================================================================

    -- Capture pre-merge insert baseline using a count of new keys not in target
    LET c_new_keys CURSOR FOR
        SELECT COUNT(1) AS CNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_TRANSFORMED T
        WHERE NOT EXISTS (
            SELECT 1
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
            WHERE TGT.PART_NUMBER = T.PART_NUMBER
        );

    OPEN c_new_keys;
    FETCH c_new_keys INTO v_inserted_count;
    CLOSE c_new_keys;

    -- Capture pre-merge update baseline: keys that already exist in target
    LET c_existing_keys CURSOR FOR
        SELECT COUNT(1) AS CNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_TRANSFORMED T
        WHERE EXISTS (
            SELECT 1
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
            WHERE TGT.PART_NUMBER = T.PART_NUMBER
        );

    OPEN c_existing_keys;
    FETCH c_existing_keys INTO v_updated_count;
    CLOSE c_existing_keys;

    -- SCD Type 1 MERGE: overwrite existing records, insert new records
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_PARTS_TRANSFORMED AS SRC
        ON TGT.PART_NUMBER = SRC.PART_NUMBER

    -- MATCHED: SCD Type 1 overwrite - update all non-key columns
    WHEN MATCHED THEN
        UPDATE SET
            TGT.PART_NAME            = SRC.PART_NAME,
            TGT.MANUFACTURER         = SRC.MANUFACTURER,
            TGT.CATEGORY             = SRC.CATEGORY,
            TGT.LIFECYCLE_STATUS     = SRC.LIFECYCLE_STATUS,
            TGT.CERTIFICATION_STATUS = SRC.CERTIFICATION_STATUS,
            TGT.LEAD_TIME_DAYS       = SRC.LEAD_TIME_DAYS,
            TGT.WEIGHT_KG            = SRC.WEIGHT_KG,
            TGT.UNIT_PRICE_USD       = SRC.UNIT_PRICE_USD,
            TGT.INSTALLATION_DATE    = SRC.INSTALLATION_DATE,
            TGT.UPDATED_AT           = SRC.UPDATED_AT,
            TGT.RISK_SCORE           = SRC.RISK_SCORE,
            TGT.LAST_MODIFIED_TS     = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ

    -- NOT MATCHED: Insert new records into target
    WHEN NOT MATCHED THEN
        INSERT (
            PART_NUMBER,
            PART_NAME,
            MANUFACTURER,
            CATEGORY,
            LIFECYCLE_STATUS,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            INSTALLATION_DATE,
            UPDATED_AT,
            CREATED_AT,
            RISK_SCORE,
            IS_DELETED,
            LAST_MODIFIED_TS
        )
        VALUES (
            SRC.PART_NUMBER,
            SRC.PART_NAME,
            SRC.MANUFACTURER,
            SRC.CATEGORY,
            SRC.LIFECYCLE_STATUS,
            SRC.CERTIFICATION_STATUS,
            SRC.LEAD_TIME_DAYS,
            SRC.WEIGHT_KG,
            SRC.UNIT_PRICE_USD,
            SRC.INSTALLATION_DATE,
            SRC.UPDATED_AT,
            SRC.CREATED_AT,
            SRC.RISK_SCORE,
            FALSE,
            CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
        );

    -- =========================================================================
    -- SECTION 8: SOFT DELETE LOGIC
    -- RULE-004: Any PART_NUMBER present in AEROSPACE_PARTS_TARGET but absent
    -- from the current source extract (TEMP_AEROSPACE_PARTS_STAGE, which
    -- represents the full current source snapshot for incremental runs) must
    -- have LIFECYCLE_STATUS set to 'Decommissioned' and IS_DELETED = TRUE.
    -- For incremental runs, soft delete applies only to records that were
    -- previously active and are no longer present in the source at all.
    -- =========================================================================

    -- Soft delete: mark records missing from source as Decommissioned
    -- For full load: any target record not in source is de

---