-- ============================================================
-- File Name   : 06_task_scheduler.sql
-- Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
-- Purpose     : Snowflake Task definition to schedule the stored
--               procedure SP_LOAD_AEROSPACE_PARTS_SCD1 to execute
--               daily at 02:00 UTC. Includes auto-resume warehouse
--               configuration, task suspension/resume controls,
--               and supporting administrative statements.
-- Generated By: SDLC_AGENT
-- Generated Date: 2025-01-31
-- Database    : GEN_AI_POC_SNOWFLAKECOE
-- Schema      : SDLC_WIZARD
-- ============================================================

-- ============================================================
-- SECTION 1: CONTEXT SETUP
-- Set the active database and schema context for all subsequent
-- statements in this file.
-- ============================================================

-- Set the active database context
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema context
USE SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD;

-- ============================================================
-- SECTION 2: WAREHOUSE AUTO-RESUME CONFIGURATION
-- Ensure the warehouse used by the task is configured with
-- AUTO_RESUME = TRUE so that it automatically starts when the
-- Snowflake Task triggers execution at 02:00 UTC, even if the
-- warehouse was previously suspended.
-- Per BRD Risk R-005: warehouse provisioning delays must be
-- mitigated via auto-resume configuration.
-- ============================================================

-- Alter the warehouse to enable auto-resume and auto-suspend
-- so it is available when the task fires and suspends after
-- idle time to control compute costs.
ALTER WAREHOUSE COMPUTE_WH
    SET AUTO_RESUME   = TRUE
        AUTO_SUSPEND  = 120
        COMMENT       = 'Warehouse configured for AEROSPACE_PARTS pipeline task. AUTO_RESUME enabled per BRD R-005 mitigation.';

-- ============================================================
-- SECTION 3: DROP EXISTING TASK (IDEMPOTENT SETUP)
-- Drop the task if it already exists to allow clean re-creation
-- during deployments or re-runs of this setup script.
-- ============================================================

-- Drop the existing task if it exists to ensure idempotent deployment
DROP TASK IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1;

-- ============================================================
-- SECTION 4: CREATE SNOWFLAKE TASK
-- Define the Snowflake Task TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
-- to call SP_LOAD_AEROSPACE_PARTS_SCD1 on a daily schedule
-- at 02:00 UTC using a CRON expression.
--
-- Business Requirements:
--   - BRD Constraint: Pipeline must run daily at 02:00 UTC
--     without manual intervention.
--   - BRD Success Criteria: SP_LOAD_AEROSPACE_PARTS_SCD1
--     executes successfully daily at 02:00 UTC.
--   - BRD Risk R-005 Mitigation: AUTO_RESUME on warehouse
--     ensures availability at scheduled execution time.
--
-- Task Configuration:
--   - WAREHOUSE     : COMPUTE_WH (auto-resume enabled above)
--   - SCHEDULE      : CRON 0 2 * * * UTC (daily at 02:00 UTC)
--   - COMMENT       : Descriptive metadata for governance
--   - BODY          : CALL to SP_LOAD_AEROSPACE_PARTS_SCD1
-- ============================================================

-- Create the Snowflake Task to schedule the aerospace parts pipeline
CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
    COMMENT   = 'Daily task to execute SP_LOAD_AEROSPACE_PARTS_SCD1 at 02:00 UTC. Implements incremental SCD Type 1 load, deduplication, soft delete, risk scoring, and reconciliation logging for AEROSPACE_PARTS_TARGET. Governed by BRD SDLC_WIZARD Aerospace Parts Pipeline.'
AS
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1();

-- ============================================================
-- SECTION 5: RESUME THE TASK
-- Snowflake Tasks are created in a SUSPENDED state by default.
-- The task must be explicitly resumed to activate the schedule.
-- Per BRD Constraint: pipeline must run daily at 02:00 UTC
-- without manual intervention after initial deployment.
-- ============================================================

-- Resume the task to activate the daily 02:00 UTC schedule
ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;

-- ============================================================
-- SECTION 6: VERIFICATION QUERIES
-- Confirm the task was created successfully, is in STARTED
-- (resumed) state, and is scheduled correctly.
-- These are informational SELECT statements for post-deployment
-- validation and can be run independently after deployment.
-- ============================================================

-- Verify task definition, schedule, state, and warehouse assignment
SHOW TASKS LIKE 'TASK_SP_LOAD_AEROSPACE_PARTS_SCD1'
    IN SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD;

-- Query INFORMATION_SCHEMA to confirm task metadata and schedule
SELECT
    TASK_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    OWNER,
    COMMENT,
    WAREHOUSE,
    SCHEDULE,
    PREDECESSORS,
    STATE,
    DEFINITION,
    CONDITION,
    ALLOW_OVERLAPPING_EXECUTION,
    ERROR_INTEGRATION,
    LAST_COMMITTED_ON,
    LAST_SUSPENDED_ON,
    CREATED
FROM
    GEN_AI_POC_SNOWFLAKECOE.INFORMATION_SCHEMA.TASKS
WHERE
    TASK_NAME   = 'TASK_SP_LOAD_AEROSPACE_PARTS_SCD1'
    AND SCHEMA_NAME = 'SDLC_WIZARD';

-- ============================================================
-- SECTION 7: TASK HISTORY QUERY
-- Query the task run history to monitor execution status,
-- duration, and errors after the task has been running.
-- Useful for SLA monitoring (BRD: 5-minute SLA for 1M records)
-- and for confirming successful daily executions.
-- ============================================================

-- Query task execution history for the last 7 days
SELECT
    NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUERY_ID,
    STATE,
    ERROR_CODE,
    ERROR_MESSAGE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    DATEDIFF('second', QUERY_START_TIME, COMPLETED_TIME) AS DURATION_SECONDS,
    RETURN_VALUE
FROM
    TABLE(
        GEN_AI_POC_SNOWFLAKECOE.INFORMATION_SCHEMA.TASK_HISTORY(
            SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
            TASK_NAME                  => 'TASK_SP_LOAD_AEROSPACE_PARTS_SCD1'
        )
    )
ORDER BY
    SCHEDULED_TIME DESC;

-- ============================================================
-- SECTION 8: ADMINISTRATIVE CONTROL STATEMENTS
-- The following statements are provided as operational controls
-- for DBAs and pipeline administrators. They are commented out
-- by default and should only be executed when required.
--
-- SUSPEND  : Temporarily pause the task (e.g., for maintenance).
-- RESUME   : Re-activate the task after suspension.
-- DROP     : Permanently remove the task (use with caution).
-- ============================================================

-- [ADMIN USE ONLY] Suspend the task to pause scheduled execution
-- ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 SUSPEND;

-- [ADMIN USE ONLY] Resume the task to re-activate scheduled execution
-- ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;

-- [ADMIN USE ONLY] Execute the task manually for ad-hoc or testing runs
-- EXECUTE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1;

-- [ADMIN USE ONLY] Drop the task permanently (irreversible)
-- DROP TASK IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1;

-- ============================================================
-- END OF FILE: 06_task_scheduler.sql
-- ============================================================