-- ============================================================
-- FILE HEADER
-- Object Name  : 06_task_schedule.sql
-- Purpose      : Snowflake Task TASK_LOAD_AEROSPACE_PARTS
--                configured to execute stored procedure
--                SP_LOAD_AEROSPACE_PARTS_SCD1 daily at 02:00 UTC
--                as part of the Aerospace Parts Inventory
--                Data Integration pipeline.
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-01
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- ============================================================

-- ============================================================
-- SECTION 1: CONTEXT SETUP
-- Set the active database and schema for all subsequent
-- statements in this file.
-- ============================================================

-- Set the active database context
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema context
USE SCHEMA SDLC_WIZARD;

-- ============================================================
-- SECTION 2: DROP EXISTING TASK (IF ANY)
-- Drop the task if it already exists to allow a clean
-- recreation. This ensures idempotent deployment.
-- ============================================================

-- Drop the existing task if it exists to allow clean recreation
DROP TASK IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_LOAD_AEROSPACE_PARTS;

-- ============================================================
-- SECTION 3: CREATE SNOWFLAKE TASK
-- Create the scheduled Snowflake Task TASK_LOAD_AEROSPACE_PARTS
-- to invoke SP_LOAD_AEROSPACE_PARTS_SCD1 daily at 02:00 UTC.
--
-- Task Configuration Details:
--   - WAREHOUSE       : Uses the current/default warehouse.
--                       Update WAREHOUSE name as appropriate
--                       for your Snowflake environment.
--   - SCHEDULE        : CRON expression '0 2 * * *' triggers
--                       the task every day at 02:00 UTC.
--   - TIMEZONE        : UTC is explicitly specified to ensure
--                       consistent scheduling regardless of
--                       account-level timezone settings.
--   - COMMENT         : Descriptive metadata for the task.
--   - BODY            : Calls the stored procedure
--                       SP_LOAD_AEROSPACE_PARTS_SCD1 which
--                       performs incremental load,
--                       deduplication, transformation,
--                       SCD Type 1 MERGE, soft delete, and
--                       reconciliation logging.
-- ============================================================

-- Create the daily scheduled task to execute the aerospace
-- parts SCD1 load stored procedure at 02:00 UTC every day
CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_LOAD_AEROSPACE_PARTS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
    COMMENT   = 'Daily task to execute SP_LOAD_AEROSPACE_PARTS_SCD1 at 02:00 UTC. Performs incremental load, deduplication, exclusion, transformation, RISK_SCORE derivation, SCD Type 1 MERGE, soft delete, and reconciliation logging for the Aerospace Parts Inventory pipeline.'
AS
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1();

-- ============================================================
-- SECTION 4: RESUME THE TASK
-- Snowflake Tasks are created in a SUSPENDED state by default.
-- The ALTER TASK ... RESUME statement activates the task so
-- that it begins executing on its defined schedule.
-- ============================================================

-- Resume (activate) the task so it begins running on schedule
ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_LOAD_AEROSPACE_PARTS RESUME;

-- ============================================================
-- SECTION 5: VERIFICATION QUERIES
-- Queries to confirm the task has been created correctly,
-- is in the STARTED (resumed) state, and is configured with
-- the expected schedule and procedure call.
-- ============================================================

-- Verify the task definition, state, and schedule configuration
SHOW TASKS LIKE 'TASK_LOAD_AEROSPACE_PARTS'
    IN SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD;

-- Query the INFORMATION_SCHEMA to confirm task metadata
-- including schedule, state, and definition
SELECT
    TASK_NAME,
    STATE,
    SCHEDULE,
    DEFINITION,
    COMMENT,
    CREATED,
    LAST_ALTERED
FROM
    GEN_AI_POC_SNOWFLAKECOE.INFORMATION_SCHEMA.TASKS
WHERE
    TASK_SCHEMA = 'SDLC_WIZARD'
    AND TASK_NAME = 'TASK_LOAD_AEROSPACE_PARTS';

-- ============================================================
-- SECTION 6: TASK HISTORY QUERY
-- Query the TASK_HISTORY table function to monitor past
-- and upcoming executions of the task. Useful for
-- operational monitoring and SLA validation.
-- ============================================================

-- Query task execution history for the last 7 days
-- to monitor run status, duration, and any errors
SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE,
    QUERY_ID,
    RUN_ID
FROM
    TABLE(
        GEN_AI_POC_SNOWFLAKECOE.INFORMATION_SCHEMA.TASK_HISTORY(
            SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
            TASK_NAME                  => 'TASK_LOAD_AEROSPACE_PARTS'
        )
    )
ORDER BY
    SCHEDULED_TIME DESC;

-- ============================================================
-- SECTION 7: OPTIONAL TASK MANAGEMENT STATEMENTS
-- The following statements are provided as operational
-- utilities for suspending or manually triggering the task.
-- They are commented out by default and should be executed
-- only when required by operations or deployment processes.
-- ============================================================

-- Suspend the task (use during maintenance windows or
-- when pipeline execution needs to be paused):
-- ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_LOAD_AEROSPACE_PARTS SUSPEND;

-- Manually trigger an immediate execution of the task
-- outside of its scheduled window (useful for testing
-- or on-demand backfill runs):
-- EXECUTE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_LOAD_AEROSPACE_PARTS;

-- ============================================================
-- END OF FILE: 06_task_schedule.sql
-- ============================================================