-- ============================================================
-- File Name   : 07_grants_and_permissions.sql
-- Object Name : Grants and Permissions for Aerospace Parts Pipeline
-- Purpose     : GRANT statements for roles and privileges required
--               to execute the stored procedure, task, and access
--               all pipeline tables in GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
-- Generated By: SDLC_AGENT
-- Generated Date: 2025-01-31
-- ============================================================

-- ============================================================
-- SECTION 1: DATABASE AND SCHEMA USAGE GRANTS
-- Grant USAGE on the target database and schema to pipeline roles
-- ============================================================

-- Grant USAGE on the database to the ETL execution role
GRANT USAGE ON DATABASE GEN_AI_POC_SNOWFLAKECOE
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant USAGE on the database to the read-only reporting role
GRANT USAGE ON DATABASE GEN_AI_POC_SNOWFLAKECOE
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant USAGE on the database to the pipeline admin role
GRANT USAGE ON DATABASE GEN_AI_POC_SNOWFLAKECOE
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant USAGE on the schema to the ETL execution role
GRANT USAGE ON SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant USAGE on the schema to the read-only reporting role
GRANT USAGE ON SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant USAGE on the schema to the pipeline admin role
GRANT USAGE ON SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 2: WAREHOUSE USAGE GRANTS
-- Grant USAGE on the compute warehouse to pipeline roles
-- ============================================================

-- Grant USAGE on the warehouse to the ETL execution role
-- Required for stored procedure and task execution
GRANT USAGE ON WAREHOUSE AEROSPACE_ETL_WH
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant USAGE on the warehouse to the pipeline admin role
GRANT USAGE ON WAREHOUSE AEROSPACE_ETL_WH
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant OPERATE on the warehouse to the ETL execution role
-- Required to resume/suspend warehouse during task execution
GRANT OPERATE ON WAREHOUSE AEROSPACE_ETL_WH
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant OPERATE on the warehouse to the pipeline admin role
GRANT OPERATE ON WAREHOUSE AEROSPACE_ETL_WH
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 3: SOURCE TABLE GRANTS (AEROSPACE_PARTS_SOURCE)
-- Grant SELECT on the source staging table to pipeline roles
-- ============================================================

-- Grant SELECT on AEROSPACE_PARTS_SOURCE to the ETL execution role
-- Required for incremental load and deduplication logic in SP_LOAD_AEROSPACE_PARTS_SCD1
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant SELECT on AEROSPACE_PARTS_SOURCE to the pipeline admin role
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant INSERT on AEROSPACE_PARTS_SOURCE to the ETL execution role
-- Required for loading raw data into the staging table
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant INSERT on AEROSPACE_PARTS_SOURCE to the pipeline admin role
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant TRUNCATE on AEROSPACE_PARTS_SOURCE to the ETL execution role
-- Required for staging table refresh operations
GRANT TRUNCATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant TRUNCATE on AEROSPACE_PARTS_SOURCE to the pipeline admin role
GRANT TRUNCATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 4: TARGET TABLE GRANTS (AEROSPACE_PARTS_TARGET)
-- Grant DML and SELECT privileges on the target table
-- ============================================================

-- Grant SELECT on AEROSPACE_PARTS_TARGET to the ETL execution role
-- Required for SCD1 merge logic and reconciliation count queries
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant SELECT on AEROSPACE_PARTS_TARGET to the read-only reporting role
-- Required for downstream reporting and compliance queries
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant SELECT on AEROSPACE_PARTS_TARGET to the pipeline admin role
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant INSERT on AEROSPACE_PARTS_TARGET to the ETL execution role
-- Required for MERGE INSERT branch in SCD1 logic
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant INSERT on AEROSPACE_PARTS_TARGET to the pipeline admin role
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant UPDATE on AEROSPACE_PARTS_TARGET to the ETL execution role
-- Required for MERGE UPDATE branch (SCD1 overwrite) and soft delete updates
GRANT UPDATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant UPDATE on AEROSPACE_PARTS_TARGET to the pipeline admin role
GRANT UPDATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant DELETE on AEROSPACE_PARTS_TARGET to the ETL execution role
-- Required for any physical delete operations if needed in future phases
GRANT DELETE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant DELETE on AEROSPACE_PARTS_TARGET to the pipeline admin role
GRANT DELETE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 5: CONTROL TABLE GRANTS (ETL_CONTROL_LOG)
-- Grant DML and SELECT privileges on the ETL control/tracking table
-- ============================================================

-- Grant SELECT on ETL_CONTROL_LOG to the ETL execution role
-- Required to read last_successful_execution_timestamp for incremental load
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant SELECT on ETL_CONTROL_LOG to the pipeline admin role
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant INSERT on ETL_CONTROL_LOG to the ETL execution role
-- Required to write new execution timestamps after successful pipeline runs
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant INSERT on ETL_CONTROL_LOG to the pipeline admin role
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant UPDATE on ETL_CONTROL_LOG to the ETL execution role
-- Required to update the last_successful_execution_timestamp record
GRANT UPDATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant UPDATE on ETL_CONTROL_LOG to the pipeline admin role
GRANT UPDATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant DELETE on ETL_CONTROL_LOG to the pipeline admin role
-- Required for administrative reset of control log entries
GRANT DELETE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 6: RECONCILIATION LOG TABLE GRANTS (ETL_RECONCILIATION_LOG)
-- Grant DML and SELECT privileges on the reconciliation audit table
-- ============================================================

-- Grant SELECT on ETL_RECONCILIATION_LOG to the ETL execution role
-- Required for reconciliation count queries within the stored procedure
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant SELECT on ETL_RECONCILIATION_LOG to the read-only reporting role
-- Required for audit and compliance reporting on pipeline run history
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant SELECT on ETL_RECONCILIATION_LOG to the pipeline admin role
GRANT SELECT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant INSERT on ETL_RECONCILIATION_LOG to the ETL execution role
-- Required to write per-run audit records after every pipeline execution (RULE-010)
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant INSERT on ETL_RECONCILIATION_LOG to the pipeline admin role
GRANT INSERT ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant UPDATE on ETL_RECONCILIATION_LOG to the pipeline admin role
-- Required for administrative corrections to reconciliation log entries
GRANT UPDATE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant DELETE on ETL_RECONCILIATION_LOG to the pipeline admin role
-- Required for administrative purge of old reconciliation log records
GRANT DELETE ON TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 7: STORED PROCEDURE GRANTS (SP_LOAD_AEROSPACE_PARTS_SCD1)
-- Grant USAGE and EXECUTE privileges on the stored procedure
-- ============================================================

-- Grant USAGE on the stored procedure to the ETL execution role
-- Required to call SP_LOAD_AEROSPACE_PARTS_SCD1 from the Snowflake Task
GRANT USAGE ON PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant USAGE on the stored procedure to the pipeline admin role
-- Required for manual execution and administrative testing
GRANT USAGE ON PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 8: TASK GRANTS (AEROSPACE_PARTS_DAILY_TASK)
-- Grant MONITOR and OPERATE privileges on the Snowflake Task
-- ============================================================

-- Grant MONITOR on the task to the ETL execution role
-- Required to view task run history and status
GRANT MONITOR ON TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_DAILY_TASK
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant MONITOR on the task to the read-only reporting role
-- Required for SLA monitoring and pipeline observability
GRANT MONITOR ON TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_DAILY_TASK
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant MONITOR on the task to the pipeline admin role
GRANT MONITOR ON TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_DAILY_TASK
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- Grant OPERATE on the task to the ETL execution role
-- Required to resume, suspend, and execute the Snowflake Task
GRANT OPERATE ON TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_DAILY_TASK
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant OPERATE on the task to the pipeline admin role
-- Required for administrative control of the task schedule
GRANT OPERATE ON TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_DAILY_TASK
    TO ROLE AEROSPACE_PIPELINE_ADMIN_ROLE;

-- ============================================================
-- SECTION 9: FUTURE TABLE GRANTS (ALL TABLES IN SCHEMA)
-- Grant privileges on all current and future tables in the schema
-- to ensure new pipeline objects are automatically accessible
-- ============================================================

-- Grant SELECT on all existing tables in the schema to the ETL execution role
GRANT SELECT ON ALL TABLES IN SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
    TO ROLE AEROSPACE_ETL_ROLE;

-- Grant SELECT on all existing tables in the schema to the reporting role
GRANT SELECT ON ALL TABLES IN SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD
    TO ROLE AEROSPACE_REPORTING_ROLE;

-- Grant SELECT on all existing tables in the schema to the pipeline admin role
GRANT SELECT ON ALL TABLES IN SCHEMA GEN_AI_POC_SNOWFLAKECOE.SDL

---

### FILE: 08_validation_and_qa_queries.sql ###