-- ============================================================
-- File Header
-- Object Name  : 07_validation_acceptance_tests.sql
-- Purpose      : Validation queries covering all nine acceptance
--                criteria for the Aerospace Parts Inventory
--                Data Integration pipeline. Tests include
--                deduplication, exclusion, RISK_SCORE correctness,
--                soft delete, reconciliation log accuracy, and
--                idempotency checks.
-- Generated By : SDLC_AGENT
-- Generated Date: 2025-01-01
-- Database     : GEN_AI_POC_SNOWFLAKECOE
-- Schema       : SDLC_WIZARD
-- ============================================================

-- Set the active database and schema context
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- ============================================================
-- SECTION 1: AC-001
-- Acceptance Criterion: All records in AEROSPACE_PARTS_TARGET
-- have a valid PART_NUMBER (not NULL, not empty string).
-- Expected Result: Zero rows returned (no invalid PART_NUMBERs).
-- ============================================================

-- AC-001: Validate that no NULL or empty PART_NUMBER exists in target
SELECT
    'AC-001' AS TEST_ID,
    'All records have valid non-null, non-empty PART_NUMBER' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE PART_NUMBER IS NULL
   OR TRIM(PART_NUMBER) = '';

-- ============================================================
-- SECTION 2: AC-002
-- Acceptance Criterion: No duplicate PART_NUMBER values exist
-- in AEROSPACE_PARTS_TARGET after the pipeline run.
-- Expected Result: Zero rows returned (no duplicates).
-- ============================================================

-- AC-002: Validate deduplication - each PART_NUMBER appears exactly once in target
SELECT
    'AC-002' AS TEST_ID,
    'No duplicate PART_NUMBER in AEROSPACE_PARTS_TARGET' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM (
    -- Subquery: find any PART_NUMBER with more than one row
    SELECT
        PART_NUMBER,
        COUNT(*) AS RECORD_COUNT
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    GROUP BY PART_NUMBER
    HAVING COUNT(*) > 1
) DUPLICATES;

-- AC-002 Detail: Show which PART_NUMBERs are duplicated (diagnostic)
SELECT
    'AC-002-DETAIL' AS TEST_ID,
    PART_NUMBER,
    COUNT(*) AS DUPLICATE_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
GROUP BY PART_NUMBER
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;

-- ============================================================
-- SECTION 3: AC-003
-- Acceptance Criterion: MANUFACTURER values in target are stored
-- in CamelCase (INITCAP) format, not all-uppercase or all-lowercase.
-- Expected Result: Zero rows where MANUFACTURER differs from
-- its INITCAP equivalent (excluding NULLs).
-- ============================================================

-- AC-003: Validate MANUFACTURER transformation to INITCAP (CamelCase)
SELECT
    'AC-003' AS TEST_ID,
    'MANUFACTURER values are stored in INITCAP (CamelCase) format' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER IS NOT NULL
  AND MANUFACTURER <> INITCAP(MANUFACTURER);

-- AC-003 Detail: Show records where MANUFACTURER is not in INITCAP format (diagnostic)
SELECT
    'AC-003-DETAIL' AS TEST_ID,
    PART_NUMBER,
    MANUFACTURER AS STORED_MANUFACTURER,
    INITCAP(MANUFACTURER) AS EXPECTED_MANUFACTURER
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER IS NOT NULL
  AND MANUFACTURER <> INITCAP(MANUFACTURER)
ORDER BY PART_NUMBER;

-- ============================================================
-- SECTION 4: AC-003 (continued)
-- Acceptance Criterion: WEIGHT_KG values <= 0 are stored as NULL
-- in AEROSPACE_PARTS_TARGET.
-- Expected Result: Zero rows where WEIGHT_KG <= 0.
-- ============================================================

-- AC-003b: Validate WEIGHT_KG transformation - no zero or negative values
SELECT
    'AC-003b' AS TEST_ID,
    'WEIGHT_KG values <= 0 are stored as NULL in target' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG IS NOT NULL
  AND WEIGHT_KG <= 0;

-- AC-003c: Validate UNIT_PRICE_USD is rounded to 2 decimal places
SELECT
    'AC-003c' AS TEST_ID,
    'UNIT_PRICE_USD values are rounded to 2 decimal places' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD IS NOT NULL
  AND UNIT_PRICE_USD <> ROUND(UNIT_PRICE_USD, 2);

-- ============================================================
-- SECTION 5: AC-004
-- Acceptance Criterion: Records with LIFECYCLE_STATUS = 'End of Life'
-- AND INSTALLATION_DATE older than 3 years are NOT present in
-- AEROSPACE_PARTS_TARGET.
-- Expected Result: Zero rows returned (all such records excluded).
-- ============================================================

-- AC-004: Validate exclusion of End of Life records older than 3 years
SELECT
    'AC-004' AS TEST_ID,
    'End of Life records with INSTALLATION_DATE > 3 years old are excluded from target' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE LIFECYCLE_STATUS = 'End of Life'
  AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

-- AC-004 Detail: Show any excluded records that incorrectly appear in target (diagnostic)
SELECT
    'AC-004-DETAIL' AS TEST_ID,
    PART_NUMBER,
    LIFECYCLE_STATUS,
    INSTALLATION_DATE,
    DATEADD(YEAR, -3, CURRENT_DATE()) AS CUTOFF_DATE
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE LIFECYCLE_STATUS = 'End of Life'
  AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
ORDER BY INSTALLATION_DATE;

-- AC-004 Supplemental: Confirm excluded records exist in source but not in target
SELECT
    'AC-004-SUPP' AS TEST_ID,
    'Excluded records exist in source but are absent from target' AS TEST_DESCRIPTION,
    COUNT(*) AS EXCLUDED_IN_SOURCE_COUNT,
    CASE
        WHEN COUNT(*) > 0 THEN 'PASS - Exclusion records found in source as expected'
        ELSE 'INFO - No exclusion candidate records found in source'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE SRC
WHERE SRC.LIFECYCLE_STATUS = 'End of Life'
  AND SRC.INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
  AND NOT EXISTS (
      SELECT 1
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
      WHERE TGT.PART_NUMBER = SRC.PART_NUMBER
        AND TGT.PART_STATUS <> 'Decommissioned'
  );

-- ============================================================
-- SECTION 6: AC-005
-- Acceptance Criterion: Records with LIFECYCLE_STATUS = 'End of Life'
-- AND INSTALLATION_DATE within the last 3 years ARE present in
-- AEROSPACE_PARTS_TARGET (not excluded).
-- Expected Result: These records should exist in target.
-- ============================================================

-- AC-005: Validate that End of Life records within 3 years are NOT excluded
SELECT
    'AC-005' AS TEST_ID,
    'End of Life records with INSTALLATION_DATE within 3 years are present in target' AS TEST_DESCRIPTION,
    SRC_COUNT.SOURCE_RECORDS,
    TGT_COUNT.TARGET_RECORDS,
    CASE
        WHEN SRC_COUNT.SOURCE_RECORDS = 0 THEN 'INFO - No such records in source'
        WHEN TGT_COUNT.TARGET_RECORDS >= SRC_COUNT.SOURCE_RECORDS THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM (
    -- Count End of Life records within 3 years in source
    SELECT COUNT(DISTINCT PART_NUMBER) AS SOURCE_RECORDS
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE LIFECYCLE_STATUS = 'End of Life'
      AND INSTALLATION_DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
) SRC_COUNT,
(
    -- Count End of Life records within 3 years in target
    SELECT COUNT(DISTINCT PART_NUMBER) AS TARGET_RECORDS
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    WHERE LIFECYCLE_STATUS = 'End of Life'
      AND INSTALLATION_DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
      AND PART_STATUS <> 'Decommissioned'
) TGT_COUNT;

-- ============================================================
-- SECTION 7: AC-006
-- Acceptance Criterion: RISK_SCORE values match expected outcomes
-- based on certification status and lead time business rules:
--   HIGH RISK   : CERTIFICATION_STATUS NOT IN ('FAA','EASA','Dual') OR LEAD_TIME_DAYS > 90
--   MEDIUM RISK : CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
--   LOW RISK    : CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 90
-- Note: HIGH RISK takes precedence, then MEDIUM RISK, then LOW RISK.
-- ============================================================

-- AC-006: Validate RISK_SCORE derivation logic for HIGH RISK records
SELECT
    'AC-006-HIGH' AS TEST_ID,
    'HIGH RISK records: CERTIFICATION_STATUS not in FAA/EASA/Dual OR LEAD_TIME_DAYS > 90' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'High Risk'
  AND NOT (
      CERTIFICATION_STATUS NOT IN ('FAA', 'EASA', 'Dual')
      OR LEAD_TIME_DAYS > 90
  );

-- AC-006: Validate RISK_SCORE derivation logic for MEDIUM RISK records
SELECT
    'AC-006-MEDIUM' AS TEST_ID,
    'MEDIUM RISK records: CERTIFICATION_STATUS = Pending OR LEAD_TIME_DAYS > 120' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'Medium Risk'
  AND NOT (
      (CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120)
      AND NOT (
          CERTIFICATION_STATUS NOT IN ('FAA', 'EASA', 'Dual')
          OR LEAD_TIME_DAYS > 90
      )
  );

-- AC-006: Validate RISK_SCORE derivation logic for LOW RISK records
SELECT
    'AC-006-LOW' AS TEST_ID,
    'LOW RISK records: CERTIFICATION_STATUS in FAA/EASA/Dual AND LEAD_TIME_DAYS <= 90' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'Low Risk'
  AND NOT (
      CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual')
      AND LEAD_TIME_DAYS <= 90
  );

-- AC-006: Validate no records have NULL or unexpected RISK_SCORE values
SELECT
    'AC-006-NULL' AS TEST_ID,
    'No NULL or unexpected RISK_SCORE values in target' AS TEST_DESCRIPTION,
    COUNT(*) AS FAILING_RECORD_COUNT,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE IS NULL
   OR RISK_SCORE NOT IN ('High Risk', 'Medium Risk', 'Low Risk');

-- AC-006 Detail: Show RISK_SCORE distribution for review
SELECT
    'AC-006-DIST' AS TEST_ID,
    RISK_SCORE,
    CERTIFICATION_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
GROUP BY RISK_SCORE, CERTIFICATION_STATUS
ORDER BY RISK_SCORE, CERTIFICATION_STATUS;

-- AC-006 Detail: Show specific test cases for RISK_SCORE validation
SELECT
    'AC-006-CASES' AS TEST_ID,
    PART_NUMBER,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,