-- =============================================================================
-- Object Name   : 08_validation_and_qa_queries.sql
-- Purpose       : QA and validation SQL queries to verify CamelCase transformation,
--                 WEIGHT_KG values, UNIT_PRICE_USD rounding, exclusion logic,
--                 RISK_SCORE accuracy, soft delete, and reconciliation log
--                 completeness for the AEROSPACE_PARTS pipeline.
-- Generated By  : SDLC_AGENT
-- Generated Date: 2025-01-31
-- Database      : GEN_AI_POC_SNOWFLAKECOE
-- Schema        : SDLC_WIZARD
-- =============================================================================

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- =============================================================================
-- SECTION 1: CAMELCASE TRANSFORMATION VALIDATION (AC-003 / RULE-006)
-- Verify that all MANUFACTURER values in AEROSPACE_PARTS_TARGET are in
-- CamelCase format (first letter of each word capitalized, rest lowercase).
-- Expected Result: Zero rows returned = PASS
-- =============================================================================

-- QA-001: Detect MANUFACTURER values that are fully uppercase (not CamelCase)
-- A CamelCase value should NOT equal its own UPPER() representation
-- unless it is a single character. This catches all-caps violations.
SELECT
    PART_NUMBER,
    MANUFACTURER,
    'QA-001: MANUFACTURER is fully UPPERCASE (not CamelCase)' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    MANUFACTURER IS NOT NULL
    AND LENGTH(MANUFACTURER) > 1
    AND MANUFACTURER = UPPER(MANUFACTURER)
ORDER BY PART_NUMBER;

-- QA-002: Detect MANUFACTURER values that are fully lowercase (not CamelCase)
-- A CamelCase value should NOT equal its own LOWER() representation.
SELECT
    PART_NUMBER,
    MANUFACTURER,
    'QA-002: MANUFACTURER is fully lowercase (not CamelCase)' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    MANUFACTURER IS NOT NULL
    AND LENGTH(MANUFACTURER) > 1
    AND MANUFACTURER = LOWER(MANUFACTURER)
ORDER BY PART_NUMBER;

-- QA-003: Verify CamelCase by checking that the first character of each
-- space-delimited word is uppercase. Uses INITCAP comparison.
-- Expected Result: Zero rows = PASS (all values match INITCAP output)
SELECT
    PART_NUMBER,
    MANUFACTURER,
    INITCAP(MANUFACTURER) AS EXPECTED_CAMELCASE,
    'QA-003: MANUFACTURER does not match INITCAP (CamelCase) format' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    MANUFACTURER IS NOT NULL
    AND MANUFACTURER != INITCAP(MANUFACTURER)
ORDER BY PART_NUMBER;

-- QA-004: Summary count of CamelCase compliance
-- Expected Result: FAIL_COUNT = 0
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN MANUFACTURER != INITCAP(MANUFACTURER) THEN 1 ELSE 0 END) AS FAIL_COUNT,
    SUM(CASE WHEN MANUFACTURER = INITCAP(MANUFACTURER) THEN 1 ELSE 0 END) AS PASS_COUNT,
    CASE
        WHEN SUM(CASE WHEN MANUFACTURER != INITCAP(MANUFACTURER) THEN 1 ELSE 0 END) = 0
        THEN 'PASS'
        ELSE 'FAIL'
    END AS QA_004_RESULT,
    'QA-004: CamelCase transformation summary' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER IS NOT NULL;

-- =============================================================================
-- SECTION 2: WEIGHT_KG NULL REPLACEMENT VALIDATION (AC-004 / RULE-007)
-- Verify that no WEIGHT_KG values of 0 or less (or NULL) exist in target.
-- Per RULE-007: NULL WEIGHT_KG values must be replaced with 0.01.
-- Expected Result: Zero rows returned = PASS
-- =============================================================================

-- QA-005: Detect NULL WEIGHT_KG values in target (should have been replaced)
SELECT
    PART_NUMBER,
    WEIGHT_KG,
    'QA-005: WEIGHT_KG is NULL (should have been replaced with 0.01)' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG IS NULL
ORDER BY PART_NUMBER;

-- QA-006: Detect WEIGHT_KG values that are zero or negative
SELECT
    PART_NUMBER,
    WEIGHT_KG,
    'QA-006: WEIGHT_KG is zero or negative (invalid value)' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG <= 0
ORDER BY PART_NUMBER;

-- QA-007: Verify that records originally NULL in source now have WEIGHT_KG = 0.01
-- Cross-check source vs target for NULL replacement
SELECT
    S.PART_NUMBER,
    S.WEIGHT_KG AS SOURCE_WEIGHT_KG,
    T.WEIGHT_KG AS TARGET_WEIGHT_KG,
    'QA-007: WEIGHT_KG NULL not replaced with 0.01 in target' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE S
INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
    ON S.PART_NUMBER = T.PART_NUMBER
WHERE
    S.WEIGHT_KG IS NULL
    AND T.WEIGHT_KG != 0.01
ORDER BY S.PART_NUMBER;

-- QA-008: Summary of WEIGHT_KG validation
-- Expected Result: FAIL_COUNT = 0
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN WEIGHT_KG IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN WEIGHT_KG <= 0 THEN 1 ELSE 0 END) AS ZERO_OR_NEGATIVE_COUNT,
    SUM(CASE WHEN WEIGHT_KG = 0.01 THEN 1 ELSE 0 END) AS REPLACED_WITH_DEFAULT_COUNT,
    CASE
        WHEN SUM(CASE WHEN WEIGHT_KG IS NULL OR WEIGHT_KG <= 0 THEN 1 ELSE 0 END) = 0
        THEN 'PASS'
        ELSE 'FAIL'
    END AS QA_008_RESULT,
    'QA-008: WEIGHT_KG null replacement and validity summary' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

-- =============================================================================
-- SECTION 3: UNIT_PRICE_USD ROUNDING VALIDATION (AC-005 / RULE-008)
-- Verify that all UNIT_PRICE_USD values are rounded to exactly 2 decimal places.
-- Expected Result: Zero rows returned = PASS
-- =============================================================================

-- QA-009: Detect UNIT_PRICE_USD values with more than 2 decimal places
-- ROUND(value, 2) should equal the stored value if correctly rounded
SELECT
    PART_NUMBER,
    UNIT_PRICE_USD,
    ROUND(UNIT_PRICE_USD, 2) AS EXPECTED_ROUNDED_VALUE,
    'QA-009: UNIT_PRICE_USD not rounded to 2 decimal places' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    UNIT_PRICE_USD IS NOT NULL
    AND UNIT_PRICE_USD != ROUND(UNIT_PRICE_USD, 2)
ORDER BY PART_NUMBER;

-- QA-010: Detect NULL UNIT_PRICE_USD values (should not exist if source is clean)
SELECT
    PART_NUMBER,
    UNIT_PRICE_USD,
    'QA-010: UNIT_PRICE_USD is NULL in target' AS QA_CHECK,
    'WARNING' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD IS NULL
ORDER BY PART_NUMBER;

-- QA-011: Summary of UNIT_PRICE_USD rounding validation
-- Expected Result: FAIL_COUNT = 0
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN UNIT_PRICE_USD != ROUND(UNIT_PRICE_USD, 2) THEN 1 ELSE 0 END) AS FAIL_COUNT,
    SUM(CASE WHEN UNIT_PRICE_USD = ROUND(UNIT_PRICE_USD, 2) THEN 1 ELSE 0 END) AS PASS_COUNT,
    SUM(CASE WHEN UNIT_PRICE_USD IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    CASE
        WHEN SUM(CASE WHEN UNIT_PRICE_USD != ROUND(UNIT_PRICE_USD, 2) THEN 1 ELSE 0 END) = 0
        THEN 'PASS'
        ELSE 'FAIL'
    END AS QA_011_RESULT,
    'QA-011: UNIT_PRICE_USD rounding to 2 decimal places summary' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD IS NOT NULL;

-- =============================================================================
-- SECTION 4: EXCLUSION LOGIC VALIDATION (AC-006 / RULE-005)
-- Verify that records with LIFECYCLE_STATUS = 'End of Life' AND
-- INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE()) are NOT present
-- in AEROSPACE_PARTS_TARGET.
-- Expected Result: Zero rows returned = PASS
-- =============================================================================

-- QA-012: Detect excluded records that incorrectly appear in target
-- These records should have been filtered out during the load
SELECT
    T.PART_NUMBER,
    T.LIFECYCLE_STATUS,
    T.INSTALLATION_DATE,
    DATEDIFF(DAY, T.INSTALLATION_DATE, CURRENT_DATE()) AS AGE_DAYS,
    'QA-012: Excluded record (End of Life + >3 years) found in target' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
WHERE
    T.LIFECYCLE_STATUS = 'End of Life'
    AND T.INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
ORDER BY T.PART_NUMBER;

-- QA-013: Verify exclusion count matches between source and reconciliation log
-- Count records in source that should have been excluded
SELECT
    COUNT(*) AS SOURCE_EXCLUSION_COUNT,
    'QA-013: Count of records in source that meet exclusion criteria' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
WHERE
    LIFECYCLE_STATUS = 'End of Life'
    AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

-- QA-014: Cross-validate exclusion count against latest reconciliation log entry
SELECT
    R.RUN_ID,
    R.RUN_TIMESTAMP,
    R.EXCLUSION_COUNT AS LOGGED_EXCLUSION_COUNT,
    (
        SELECT COUNT(*)
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE
            LIFECYCLE_STATUS = 'End of Life'
            AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
    ) AS COMPUTED_EXCLUSION_COUNT,
    CASE
        WHEN R.EXCLUSION_COUNT = (
            SELECT COUNT(*)
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE
                LIFECYCLE_STATUS = 'End of Life'
                AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
        )
        THEN 'PASS'
        ELSE 'FAIL'
    END AS QA_014_RESULT,
    'QA-014: Exclusion count in reconciliation log vs computed' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG R
WHERE R.RUN_TIMESTAMP = (
    SELECT MAX(RUN_TIMESTAMP)
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
);

-- QA-015: Summary of exclusion logic validation
SELECT
    COUNT(*) AS EXCLUDED_RECORDS_IN_TARGET,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS QA_015_RESULT,
    'QA-015: Exclusion logic summary - End of Life records older than 3 years must not exist in target' AS QA_CHECK
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    LIFECYCLE_STATUS = 'End of Life'
    AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

-- =============================================================================
-- SECTION 5: RISK_SCORE DERIVATION VALIDATION (RULE-009)
-- Verify RISK_SCORE is correctly derived based on:
--   High Risk   : DAYS_IN_SERVICE > 90
--   Medium Risk : CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
--   Low Risk    : CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60
--   Medium Risk : All other cases (ELSE)
-- Expected Result: Zero rows returned = PASS
-- =============================================================================

-- QA-016: Detect records where RISK_SCORE = 'High Risk' but DAYS_IN_SERVICE <= 90
SELECT
    PART_NUMBER,
    RISK_SCORE,
    DAYS_IN_SERVICE,
    CERTIFICATION_STATUS,
    LEAD_TIME_DAYS,
    'QA-016: RISK_SCORE=High Risk but DAYS_IN_SERVICE <= 90' AS QA_CHECK,
    'FAIL' AS QA_RESULT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE
    RISK_SCORE = 'High Risk