/*==============================================================
Object Name : DDL_SETUP_AEROSPACE_PARTS
Purpose     : Creates all required tables for the Aerospace Parts
              pipeline: AEROSPACE_PARTS_TARGET (SCD1 target),
              PIPELINE_CONTROL (last-run timestamp tracking), and
              ETL_RECONCILIATION_LOG (mandatory audit logging).
              Implements CREATE TABLE IF NOT EXISTS so re-runs are safe.
Generated By: SDLC_AGENT
Generated Date: 2025-01-31
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Establish session context — target database and schema
---------------------------------------------------------

-- Set the active database for all subsequent DDL statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set the active schema so all objects land in the correct namespace
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: DDL — Create AEROSPACE_PARTS_TARGET table
--          This is the SCD Type 1 target table (RULE-001, DEC-001).
--          PART_NUMBER is the business key (DEC-002).
--          Includes all source columns plus derived/pipeline columns:
--          RISK_SCORE (RULE-009), MANUFACTURER in CamelCase (RULE-006),
--          WEIGHT_KG with NULL replacement (RULE-007),
--          UNIT_PRICE_USD rounded to 2dp (RULE-008),
--          LIFECYCLE_STATUS for soft-delete (RULE-004),
--          LOAD_TIMESTAMP and UPDATED_AT for audit/incremental (RULE-003).
---------------------------------------------------------

-- Create the SCD1 target table if it does not already exist.
-- All column names are UPPERCASE unquoted per naming conventions.
-- AC-003: MANUFACTURER stored as CamelCase after transformation.
-- AC-004: WEIGHT_KG will never be 0 or less after load.
-- AC-005: UNIT_PRICE_USD stored rounded to 2 decimal places.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER          VARCHAR(100)   NOT NULL,   -- Business key (DEC-002, RULE-002)
    PART_NAME            VARCHAR(255),              -- Descriptive name of the part
    MANUFACTURER         VARCHAR(255),              -- CamelCase transformed (RULE-006, AC-003)
    CATEGORY             VARCHAR(100),              -- Part category / classification
    LIFECYCLE_STATUS     VARCHAR(50),               -- Active, Decommissioned, End of Life, etc. (RULE-004)
    INSTALLATION_DATE    DATE,                      -- Date part was installed (used in RULE-005 exclusion)
    WEIGHT_KG            NUMBER(18,4),              -- Weight; NULLs replaced with 0.0 (RULE-007, AC-004)
    UNIT_PRICE_USD       NUMBER(18,2),              -- Price rounded to 2 decimal places (RULE-008, AC-005)
    LEAD_TIME_DAYS       NUMBER(10),                -- Procurement lead time in days (used in RULE-009)
    CERTIFICATION_STATUS VARCHAR(50),               -- Certification body: FAA, EASA, Dual, Pending (RULE-009)
    LAST_INSPECTED_DATE  DATE,                      -- Date of last inspection (used in RULE-009 High Risk)
    UPDATED_AT           TIMESTAMP_NTZ,             -- Source last-updated timestamp (RULE-003 incremental key)
    RISK_SCORE           VARCHAR(20),               -- Derived: High Risk / Medium Risk / Low Risk (RULE-009)
    LOAD_TIMESTAMP       TIMESTAMP_NTZ              -- Pipeline load timestamp for audit trail
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: DDL — Create PIPELINE_CONTROL table
--          Stores the last successful execution timestamp used
--          for incremental load logic (RULE-003, DEC-004).
--          On first run this table will be empty, triggering full load.
---------------------------------------------------------

-- Create the pipeline control/metadata table if it does not already exist.
-- PIPELINE_NAME allows multiple pipelines to share this control table.
-- LAST_SUCCESSFUL_RUN is NULL on first run, which triggers a full load (RULE-003).
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.PIPELINE_CONTROL (
    PIPELINE_NAME        VARCHAR(200)   NOT NULL,   -- Logical name of the pipeline
    LAST_SUCCESSFUL_RUN  TIMESTAMP_NTZ,             -- NULL = first run → full load (RULE-003)
    UPDATED_AT           TIMESTAMP_NTZ              -- When this control record was last updated
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: DDL — Create ETL_RECONCILIATION_LOG table
--          Mandatory reconciliation logging after every pipeline run
--          (RULE-010, DEC-005, AC-002).
--          Captures source_count, target_count, inserted_count,
--          updated_count, decommissioned_count, exclusion_count,
--          and run_timestamp.
---------------------------------------------------------

-- Create the reconciliation log table if it does not already exist.
-- Every pipeline execution must insert exactly one row here (RULE-010).
-- STATUS captures SUCCESS or FAILURE for SLA monitoring.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    LOG_ID               NUMBER AUTOINCREMENT PRIMARY KEY, -- Surrogate key for log entries
    PIPELINE_NAME        VARCHAR(200),              -- Name of the pipeline that produced this log row
    RUN_TIMESTAMP        TIMESTAMP_NTZ,             -- Wall-clock time the pipeline run completed (RULE-010)
    SOURCE_COUNT         NUMBER,                    -- Total records read from source extract (RULE-010)
    TARGET_COUNT         NUMBER,                    -- Total records in target after load (RULE-010)
    INSERTED_COUNT       NUMBER,                    -- Net-new records inserted this run (RULE-010)
    UPDATED_COUNT        NUMBER,                    -- Existing records updated/overwritten this run (RULE-010)
    DECOMMISSIONED_COUNT NUMBER,                    -- Records soft-deleted as Decommissioned (RULE-004, RULE-010)
    EXCLUSION_COUNT      NUMBER,                    -- Records excluded by RULE-005 filter (RULE-010)
    STATUS               VARCHAR(20),               -- SUCCESS or FAILURE
    ERROR_MESSAGE        VARCHAR(4000)              -- Populated on FAILURE; NULL on SUCCESS
);