-- ============================================================
-- File Name   : 02_ddl_target_table.sql
-- Object Name : AEROSPACE_PARTS_TARGET
-- Purpose     : DDL for the AEROSPACE_PARTS_TARGET table in
--               GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD schema.
--               This table stores clean, deduplicated, and
--               transformed aerospace parts inventory data
--               loaded by SP_LOAD_AEROSPACE_PARTS_SCD1.
--               Includes all required columns: RISK_SCORE,
--               LIFECYCLE_STATUS, soft-delete support, and
--               full audit metadata for SCD Type 1 pipeline.
-- Generated By: SDLC_AGENT
-- Generated Date: 2025-01-31
-- ============================================================

-- ============================================================
-- SECTION 1: Database and Schema Context
-- ============================================================

-- Set the active database and schema context for all subsequent statements
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- ============================================================
-- SECTION 2: Create AEROSPACE_PARTS_TARGET Table
-- ============================================================

-- Create the AEROSPACE_PARTS_TARGET table if it does not already exist.
-- This is the primary analytics-ready target table for the aerospace
-- parts inventory pipeline. It implements SCD Type 1 (overwrite) logic
-- keyed on PART_NUMBER. Includes derived columns RISK_SCORE and
-- LIFECYCLE_STATUS, soft-delete support via IS_DELETED flag, and
-- full ETL audit metadata columns.
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (

    -- ----------------------------------------------------------
    -- Primary Business Key
    -- ----------------------------------------------------------
    -- Unique identifier for each aerospace part across all systems.
    -- Used as the merge key for SCD Type 1 upsert operations.
    PART_NUMBER                 VARCHAR(100)        NOT NULL,

    -- ----------------------------------------------------------
    -- Core Part Attributes
    -- ----------------------------------------------------------
    -- Descriptive name of the aerospace part
    PART_NAME                   VARCHAR(255),

    -- Part category or classification (e.g., Structural, Avionics, Propulsion)
    PART_CATEGORY               VARCHAR(100),

    -- Manufacturer name, stored in CamelCase format after transformation
    -- (RULE-006: MANUFACTURER must be converted to CamelCase)
    MANUFACTURER                VARCHAR(255),

    -- Supplier name associated with the part
    SUPPLIER_NAME               VARCHAR(255),

    -- Country of origin for the part
    COUNTRY_OF_ORIGIN           VARCHAR(100),

    -- ----------------------------------------------------------
    -- Physical and Pricing Attributes
    -- ----------------------------------------------------------
    -- Weight of the part in kilograms.
    -- NULL or zero values are replaced with 0.01 per RULE-007.
    WEIGHT_KG                   NUMBER(18, 4),

    -- Unit price in USD, rounded to 2 decimal places per RULE-008.
    UNIT_PRICE_USD              NUMBER(18, 2),

    -- Quantity of parts currently available in inventory
    QUANTITY_IN_STOCK           NUMBER(18, 0),

    -- Reorder threshold quantity; triggers procurement when stock falls below
    REORDER_LEVEL               NUMBER(18, 0),

    -- Lead time in days for procurement/delivery of the part
    LEAD_TIME_DAYS              NUMBER(10, 0),

    -- ----------------------------------------------------------
    -- Certification and Compliance Attributes
    -- ----------------------------------------------------------
    -- Certification status of the part.
    -- Valid values: Pending, FAA, EASA, Dual (used in RISK_SCORE derivation)
    CERTIFICATION_STATUS        VARCHAR(100),

    -- Regulatory compliance flag indicating whether the part meets
    -- all applicable aerospace regulatory requirements
    IS_COMPLIANT                BOOLEAN,

    -- Date the part was last inspected for compliance or quality
    LAST_INSPECTION_DATE        DATE,

    -- Date the part's current certification expires
    CERTIFICATION_EXPIRY_DATE   DATE,

    -- ----------------------------------------------------------
    -- Lifecycle and Installation Attributes
    -- ----------------------------------------------------------
    -- Date the part was installed or first placed into service.
    -- Used in RULE-005 exclusion logic: End of Life parts with
    -- INSTALLATION_DATE older than 3 years are excluded from load.
    INSTALLATION_DATE           DATE,

    -- Lifecycle status of the part.
    -- Examples: Active, End of Life, Decommissioned, Obsolete.
    -- Soft-deleted records are set to 'Decommissioned' per RULE-004.
    LIFECYCLE_STATUS            VARCHAR(100),

    -- ----------------------------------------------------------
    -- Derived Risk Classification Column
    -- ----------------------------------------------------------
    -- Derived risk classification based on RULE-009:
    --   High Risk   : LAST_INSPECTION_DATE > 90 days ago
    --   Medium Risk : CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
    --   Low Risk    : CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
    --                 AND LEAD_TIME_DAYS <= 60
    --   Medium Risk : All other cases (default)
    RISK_SCORE                  VARCHAR(50),

    -- ----------------------------------------------------------
    -- Soft Delete Support
    -- ----------------------------------------------------------
    -- Flag indicating whether the record has been soft-deleted.
    -- Set to TRUE when a PART_NUMBER is present in the target
    -- but absent from the current source extract (RULE-004).
    -- Default is FALSE for all active records.
    IS_DELETED                  BOOLEAN             NOT NULL DEFAULT FALSE,

    -- Timestamp when the record was soft-deleted (set to Decommissioned).
    -- NULL for active records.
    DELETED_AT                  TIMESTAMP_NTZ,

    -- ----------------------------------------------------------
    -- Source Tracking Attributes
    -- ----------------------------------------------------------
    -- Timestamp from the source system indicating when the record
    -- was last updated. Used for incremental load filtering (RULE-003).
    UPDATED_AT                  TIMESTAMP_NTZ,

    -- Timestamp from the source system indicating when the record
    -- was originally created
    CREATED_AT                  TIMESTAMP_NTZ,

    -- ----------------------------------------------------------
    -- ETL Audit Metadata Columns
    -- ----------------------------------------------------------
    -- Timestamp when this record was first inserted into the target table
    ETL_INSERT_TIMESTAMP        TIMESTAMP_NTZ       NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    -- Timestamp when this record was last updated by the ETL pipeline
    ETL_UPDATE_TIMESTAMP        TIMESTAMP_NTZ       NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    -- Name of the stored procedure or process that last loaded this record
    ETL_LOAD_PROCESS            VARCHAR(255)        DEFAULT 'SP_LOAD_AEROSPACE_PARTS_SCD1',

    -- Unique run identifier for the ETL execution that last touched this record.
    -- Correlates to ETL_RECONCILIATION_LOG.RUN_ID for traceability.
    ETL_RUN_ID                  VARCHAR(100),

    -- ----------------------------------------------------------
    -- Table Constraints
    -- ----------------------------------------------------------
    -- Enforce uniqueness on the business key PART_NUMBER.
    -- Supports SCD Type 1 merge operations and prevents duplicate records.
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)

)
-- Table-level comment describing purpose and ownership
COMMENT = 'Analytics-ready target table for aerospace parts inventory data. Loaded daily by SP_LOAD_AEROSPACE_PARTS_SCD1 using SCD Type 1 (overwrite) strategy. Includes derived RISK_SCORE, CamelCase MANUFACTURER, soft-delete support, and full ETL audit metadata. Business key: PART_NUMBER. Schema: GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD. Generated by SDLC_AGENT.';

-- ============================================================
-- SECTION 3: Clustering Key Definition
-- ============================================================

-- Apply a clustering key on PART_NUMBER and UPDATED_AT to optimize
-- merge performance and incremental load query pruning for large
-- data volumes (up to 1 million records per run, per BRD SLA requirement).
-- Clustering on PART_NUMBER aligns with the SCD Type 1 merge key.
-- Clustering on UPDATED_AT supports efficient incremental filtering.
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    CLUSTER BY (PART_NUMBER, UPDATED_AT);

-- ============================================================
-- SECTION 4: Verification Query
-- ============================================================

-- Verify the table was created successfully by describing its structure.
-- This confirms all columns, data types, constraints, and clustering
-- are correctly applied before downstream pipeline objects are deployed.
DESCRIBE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;