-- =============================================================================
-- Object Name   : ETL_CONTROL_LOG
-- Purpose       : DDL for the ETL Control Log table used to track the last
--                 successful execution timestamp for incremental load logic
--                 in the SP_LOAD_AEROSPACE_PARTS_SCD1 pipeline. On each
--                 successful pipeline run, this table is updated with the
--                 latest execution timestamp so that subsequent incremental
--                 loads can filter source records using UPDATED_AT >
--                 LAST_SUCCESSFUL_EXECUTION_TS. On first run (no row present),
--                 the pipeline performs a full load of all source records.
-- Database      : GEN_AI_POC_SNOWFLAKECOE
-- Schema        : SDLC_WIZARD
-- Generated By  : SDLC_AGENT
-- Generated Date: 2025-01-31
-- =============================================================================

-- =============================================================================
-- SECTION 1: Database and Schema Context
-- Set the active database and schema for all subsequent DDL statements.
-- =============================================================================

-- Set active database context
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- Set active schema context
USE SCHEMA SDLC_WIZARD;

-- =============================================================================
-- SECTION 2: ETL_CONTROL_LOG Table Creation
-- Creates the control log table if it does not already exist. This table
-- stores one row per pipeline process name, tracking the last successful
-- execution timestamp used to drive incremental load filtering logic.
-- The PROCEDURE_NAME column acts as the logical key, allowing multiple
-- pipelines to share a single control table without conflict.
-- =============================================================================

-- Create ETL_CONTROL_LOG table to support incremental load timestamp tracking
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG (

    -- Surrogate primary key: auto-incrementing unique identifier for each row
    CONTROL_LOG_ID          NUMBER AUTOINCREMENT PRIMARY KEY,

    -- Logical key: name of the stored procedure or pipeline process this row
    -- belongs to. Allows multiple pipelines to share this control table.
    -- For this project the value will be 'SP_LOAD_AEROSPACE_PARTS_SCD1'.
    PROCEDURE_NAME          VARCHAR(255)        NOT NULL,

    -- The timestamp of the last successful end-to-end pipeline execution.
    -- Used as the lower bound filter: source records with UPDATED_AT greater
    -- than this value are included in the next incremental load.
    -- NULL indicates no prior successful run has been recorded (first run),
    -- which triggers a full load of all records from AEROSPACE_PARTS_SOURCE.
    LAST_SUCCESSFUL_EXECUTION_TS  TIMESTAMP_NTZ,

    -- The timestamp when this control row was first inserted into the table.
    -- Populated automatically at insert time using CURRENT_TIMESTAMP.
    CREATED_TS              TIMESTAMP_NTZ       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- The timestamp when this control row was most recently updated.
    -- Updated by the stored procedure at the end of each successful run.
    UPDATED_TS              TIMESTAMP_NTZ       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- The run status of the most recently completed pipeline execution.
    -- Expected values: 'SUCCESS', 'FAILED', 'IN_PROGRESS'.
    -- Allows operators to quickly identify whether the last run completed
    -- successfully before relying on LAST_SUCCESSFUL_EXECUTION_TS.
    LAST_RUN_STATUS         VARCHAR(50),

    -- Optional free-text field to capture any notes, error messages, or
    -- contextual information recorded during the last pipeline execution.
    -- Populated by the stored procedure on failure or for informational use.
    LAST_RUN_NOTES          VARCHAR(4000),

    -- The total number of source records evaluated during the last pipeline run.
    -- Provides a quick reference for volume monitoring without querying the
    -- reconciliation log.
    LAST_SOURCE_COUNT       NUMBER,

    -- The total number of records present in AEROSPACE_PARTS_TARGET at the
    -- end of the last successful pipeline run.
    LAST_TARGET_COUNT       NUMBER,

    -- Indicates whether the last run was a full load (TRUE) or an incremental
    -- load (FALSE). A full load occurs when no prior successful execution
    -- timestamp exists in this table (first run scenario).
    IS_FULL_LOAD            BOOLEAN             DEFAULT FALSE,

    -- The Snowflake session or query ID associated with the last pipeline
    -- execution. Useful for tracing execution history in Snowflake query
    -- history and for support investigations.
    LAST_QUERY_ID           VARCHAR(255),

    -- The name of the Snowflake warehouse used during the last pipeline run.
    -- Supports infrastructure monitoring and cost attribution.
    WAREHOUSE_NAME          VARCHAR(255)

);

-- =============================================================================
-- SECTION 3: Seed Initial Control Row
-- Insert the initial control row for SP_LOAD_AEROSPACE_PARTS_SCD1 if no row
-- already exists for this procedure. The LAST_SUCCESSFUL_EXECUTION_TS is set
-- to NULL to signal that the first pipeline run should perform a full load
-- of all records from AEROSPACE_PARTS_SOURCE.
-- This INSERT uses a NOT EXISTS guard to ensure idempotency: re-running this
-- script will not insert a duplicate row or overwrite an existing control row
-- that has already been updated by a live pipeline execution.
-- =============================================================================

-- Seed the initial control row for SP_LOAD_AEROSPACE_PARTS_SCD1 (idempotent)
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG (
    PROCEDURE_NAME,
    LAST_SUCCESSFUL_EXECUTION_TS,
    CREATED_TS,
    UPDATED_TS,
    LAST_RUN_STATUS,
    LAST_RUN_NOTES,
    LAST_SOURCE_COUNT,
    LAST_TARGET_COUNT,
    IS_FULL_LOAD,
    LAST_QUERY_ID,
    WAREHOUSE_NAME
)
SELECT
    'SP_LOAD_AEROSPACE_PARTS_SCD1'  AS PROCEDURE_NAME,
    NULL                            AS LAST_SUCCESSFUL_EXECUTION_TS,
    CURRENT_TIMESTAMP               AS CREATED_TS,
    CURRENT_TIMESTAMP               AS UPDATED_TS,
    'NOT_STARTED'                   AS LAST_RUN_STATUS,
    'Initial seed row. No prior execution recorded. Next run will perform full load.' AS LAST_RUN_NOTES,
    NULL                            AS LAST_SOURCE_COUNT,
    NULL                            AS LAST_TARGET_COUNT,
    FALSE                           AS IS_FULL_LOAD,
    NULL                            AS LAST_QUERY_ID,
    NULL                            AS WAREHOUSE_NAME
WHERE NOT EXISTS (
    SELECT 1
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
    WHERE PROCEDURE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1'
);

-- =============================================================================
-- SECTION 4: Verification Query
-- Select the current state of the ETL_CONTROL_LOG table to confirm that the
-- DDL and seed insert executed successfully. This query is safe to run in
-- any environment and will return the seeded row on first deployment.
-- =============================================================================

-- Verify ETL_CONTROL_LOG table structure and seeded row
SELECT
    CONTROL_LOG_ID,
    PROCEDURE_NAME,
    LAST_SUCCESSFUL_EXECUTION_TS,
    CREATED_TS,
    UPDATED_TS,
    LAST_RUN_STATUS,
    LAST_RUN_NOTES,
    LAST_SOURCE_COUNT,
    LAST_TARGET_COUNT,
    IS_FULL_LOAD,
    LAST_QUERY_ID,
    WAREHOUSE_NAME
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_CONTROL_LOG
ORDER BY CONTROL_LOG_ID ASC;